### PySpark

In [38]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("car_sales").getOrCreate()

df = spark.read.format('csv').option('inferSchema',True).option('header',True).load('C:/Users/shiva/Downloads/Car_sales.csv')

In [39]:
df.limit(3).toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch
0,Mercedes-B,CL500,954,"$85,500","$63,423",74%,GOOD,5.0,NaN,High HP,Passenger,20,141.100985,113.6,73.1,196.6,4.115,23.2,4/11/2011
1,Mercedes-B,SL-Class,3311,"$82,600","$58,600",71%,GOOD,5.0,NaN,High HP,Passenger,20,139.982294,99.0,71.3,177.1,4.125,21.1,3/17/2011
2,Porsche,Carrera Cabrio,1866,"$74,970","$67,550",90%,GOOD,3.4,300.0,High HP,Passenger,23,135.914710,92.6,69.5,174.5,3.075,17.0,7/11/2011

In [40]:
from pyspark.sql.types import *
from pyspark.sql.functions import *

In [41]:
#df_select = df.select('Manufacturer','Model','Unit Sales','Price')
df_select = df.select(col('Manufacturer'),col('Model'),col('Unit Sales'),col('Price'))

df_select.limit(5).toPandas()

  Manufacturer           Model  Unit Sales     Price
0   Mercedes-B           CL500         954  $85,500
1   Mercedes-B        SL-Class        3311  $82,600
2      Porsche  Carrera Cabrio        1866  $74,970
3   Mercedes-B           CL500         954  $85,500
4   Mercedes-B        SL-Class        3311  $82,600

In [23]:
df.show()

+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|Manufacturer|         Model|Unit Sales|   Price|Year Resale Value|Retention %|Retention Value|Engine Size|Horsepower| HP Level|Vehicle_type|Fuel Efficiency|Power Perf Factor|Wheelbase|Width|Length|Curb Weight|Fuel Capacity|Latest Launch|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|      NULL|  High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|      NULL|  High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300|  High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300|  High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
|     Porsche| Carrera Coupe|      1280|$71,020 |         $60,625 |        85%|           GOOD|        3.4|       300|  High HP|   Passenger|             21|      134.3909754|     92.6| 69.5| 174.5|      3.032|         17.0|   12/21/2012|
|       Dodge|         Viper|       916|$69,725 |         $58,470 |        84%|           GOOD|        8.0|       450|  High HP|   Passenger|             16|       188.144323|     96.2| 75.7| 176.7|      3.375|         19.0|     8/7/2011|
|  Mercedes-B|       S-Class|     16774|$69,700 |         $50,375 |        72%|           GOOD|        4.3|       275|Medium HP|   Passenger|             21|      125.2738757|    121.5| 73.1| 203.1|      4.133|         23.2|    6/13/2011|
|        Audi|            A8|      1380|$62,000 |         $39,000 |        63%|           POOR|        4.2|       310|  High HP|   Passenger|             21|      134.6568582|    113.0| 74.0| 198.2|      3.902|         23.7|    2/27/2012|
|       Lexus|         LX470|      9126|$60,105 |         $43,870 |        73%|           GOOD|        4.7|       230|Medium HP|         Car|             15|       105.760458|    112.2| 76.4| 192.5|      5.401|         25.4|   10/30/2012|
|   Chevrolet|      Corvette|     17947|$55,705 |         $36,225 |        65%|           POOR|        5.7|       345|  High HP|   Passenger|             22|        141.14115|    104.5| 73.6| 179.7|       3.21|         19.1|    5/12/2012|
|       Lexus|         LS400|      6375|$54,005 |         $40,375 |        75%|           GOOD|        4.0|       290|Medium HP|   Passenger|             22|      124.4467163|    112.2| 72.0| 196.7|       3.89|         22.5|    3/29/2012|
|      Toyota|  Land Cruiser|      9835|$51,728 |         $34,080 |        66%|           POOR|        4.7|       230|Medium HP|         Car|             15|      102.5289842|    112.2| 76.4| 192.5|      5.115|         25.4|    9/25/2011|
|  Mercedes-B|       E-Class|     27602|$49,900 |         $41,450 |        83%|           GOOD|        3.2|       221|Medium HP|   Passenger|             25|       98.2497375|    111.5| 70.8| 189.4|      3.823|         21.1|    7/12/2011|
|       Lexus|         GS400|      3334|$46,305 |         $38,955 |        84%|           GOOD|        4.0|       300|  High HP|   Passenger|             21|      125.0133574|    110.2| 70.9| 189.2|      3.693|         19.8|   11/28/2012|
|    Cadillac|      Escalade|     14785|$46,225 |         $31,245 |        68%|           POOR|        5.7|       255|Medium HP|         Car|             15|      109.5091165|    117.5| 77.0| 201.2|      5.572|         30.0|    4/17/2012|
|       Volvo|           C70|      3493|$45,500 |         $34,175 |        75%|           GOOD|        2.3|       236|Medium HP|   Passenger|             23|      101.6233572|    104.9| 71.5| 185.7|      3.601|         18.5|    4/26/2011|
|    Cadillac|       Seville|     15943|$44,475 |         $27,100 |        61%|           POOR|        4.6|       275|Medium HP|   Passenger|             22|      115.6213578|    112.2| 75.0| 201.0|      3.875|         18.5|    4/29/2011|
|     Lincoln|      Town car|     48911|$43,330 |         $21,725 |        50%|           POOR|        4.6|       215|Medium HP|   Passenger|             21|       93.9579169|    117.7| 78.2| 215.3|      4.121|         19.0|     6/4/2012|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
only showing top 20 rows

Filter

In [24]:
#df.filter((col('Manufacturer')=='Audi')).show()
df_filter = df.filter((col('Manufacturer')=='Audi') & (col('Retention Value') == 'GOOD'))

df_filter.toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch
0,Audi,A6,18780,"$33,950","$23,555",69%,GOOD,2.8,200,Medium HP,Passenger,22,84.565105,108.7,76.1,192.0,3.561,18.5,8/9/2011
1,Audi,A4,20397,"$23,990","$22,255",93%,GOOD,1.8,150,Medium HP,Passenger,27,62.777639,102.6,68.2,178.0,2.998,16.4,10/8/2011

In [25]:
df.show()

+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|Manufacturer|         Model|Unit Sales|   Price|Year Resale Value|Retention %|Retention Value|Engine Size|Horsepower| HP Level|Vehicle_type|Fuel Efficiency|Power Perf Factor|Wheelbase|Width|Length|Curb Weight|Fuel Capacity|Latest Launch|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|      NULL|  High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|      NULL|  High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300|  High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300|  High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
|     Porsche| Carrera Coupe|      1280|$71,020 |         $60,625 |        85%|           GOOD|        3.4|       300|  High HP|   Passenger|             21|      134.3909754|     92.6| 69.5| 174.5|      3.032|         17.0|   12/21/2012|
|       Dodge|         Viper|       916|$69,725 |         $58,470 |        84%|           GOOD|        8.0|       450|  High HP|   Passenger|             16|       188.144323|     96.2| 75.7| 176.7|      3.375|         19.0|     8/7/2011|
|  Mercedes-B|       S-Class|     16774|$69,700 |         $50,375 |        72%|           GOOD|        4.3|       275|Medium HP|   Passenger|             21|      125.2738757|    121.5| 73.1| 203.1|      4.133|         23.2|    6/13/2011|
|        Audi|            A8|      1380|$62,000 |         $39,000 |        63%|           POOR|        4.2|       310|  High HP|   Passenger|             21|      134.6568582|    113.0| 74.0| 198.2|      3.902|         23.7|    2/27/2012|
|       Lexus|         LX470|      9126|$60,105 |         $43,870 |        73%|           GOOD|        4.7|       230|Medium HP|         Car|             15|       105.760458|    112.2| 76.4| 192.5|      5.401|         25.4|   10/30/2012|
|   Chevrolet|      Corvette|     17947|$55,705 |         $36,225 |        65%|           POOR|        5.7|       345|  High HP|   Passenger|             22|        141.14115|    104.5| 73.6| 179.7|       3.21|         19.1|    5/12/2012|
|       Lexus|         LS400|      6375|$54,005 |         $40,375 |        75%|           GOOD|        4.0|       290|Medium HP|   Passenger|             22|      124.4467163|    112.2| 72.0| 196.7|       3.89|         22.5|    3/29/2012|
|      Toyota|  Land Cruiser|      9835|$51,728 |         $34,080 |        66%|           POOR|        4.7|       230|Medium HP|         Car|             15|      102.5289842|    112.2| 76.4| 192.5|      5.115|         25.4|    9/25/2011|
|  Mercedes-B|       E-Class|     27602|$49,900 |         $41,450 |        83%|           GOOD|        3.2|       221|Medium HP|   Passenger|             25|       98.2497375|    111.5| 70.8| 189.4|      3.823|         21.1|    7/12/2011|
|       Lexus|         GS400|      3334|$46,305 |         $38,955 |        84%|           GOOD|        4.0|       300|  High HP|   Passenger|             21|      125.0133574|    110.2| 70.9| 189.2|      3.693|         19.8|   11/28/2012|
|    Cadillac|      Escalade|     14785|$46,225 |         $31,245 |        68%|           POOR|        5.7|       255|Medium HP|         Car|             15|      109.5091165|    117.5| 77.0| 201.2|      5.572|         30.0|    4/17/2012|
|       Volvo|           C70|      3493|$45,500 |         $34,175 |        75%|           GOOD|        2.3|       236|Medium HP|   Passenger|             23|      101.6233572|    104.9| 71.5| 185.7|      3.601|         18.5|    4/26/2011|
|    Cadillac|       Seville|     15943|$44,475 |         $27,100 |        61%|           POOR|        4.6|       275|Medium HP|   Passenger|             22|      115.6213578|    112.2| 75.0| 201.0|      3.875|         18.5|    4/29/2011|
|     Lincoln|      Town car|     48911|$43,330 |         $21,725 |        50%|           POOR|        4.6|       215|Medium HP|   Passenger|             21|       93.9579169|    117.7| 78.2| 215.3|      4.121|         19.0|     6/4/2012|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
only showing top 20 rows

In [26]:
df_multi_filter = df.filter(
    (col('Horsepower').isNull()) & 
    (col('Retention Value').isin('GOOD', 'POOR'))
    )

df_multi_filter.toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch
0,Mercedes-B,CL500,954,"$85,500","$63,423",74%,GOOD,5.0,NaN,High HP,Passenger,20,141.100985,113.6,73.1,196.6,4.115,23.2,4/11/2011
1,Mercedes-B,SL-Class,3311,"$82,600","$58,600",71%,GOOD,5.0,NaN,High HP,Passenger,20,139.982294,99.0,71.3,177.1,4.125,21.1,3/17/2011
2,BMW,528i,17527,"$38,900","$36,125",93%,GOOD,2.8,NaN,Medium HP,Passenger,25,83.998724,111.4,70.9,188.0,3.472,18.5,4/4/2011
3,Acura,Integra,16919,"$21,500","$16,360",76%,GOOD,1.8,NaN,Medium HP,Passenger,28,58.280150,101.2,67.3,172.4,2.639,13.2,2/2/2012
4,Dodge,Ram Van,31038,"$18,575","$13,425",72%,GOOD,3.9,NaN,Medium HP,Car,16,70.078322,127.2,78.8,208.5,4.298,32.0,7/26/2012
5,Dodge,Dakota,111313,"$16,980","$11,260",66%,POOR,2.5,NaN,Medium HP,Car,19,49.645002,131.0,71.5,215.0,3.557,22.0,11/25/2011

In [27]:
df.withColumnRenamed('Unit Sales','Unit_Sales').show(3)

+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+--------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|Manufacturer|         Model|Unit_Sales|   Price|Year Resale Value|Retention %|Retention Value|Engine Size|Horsepower|HP Level|Vehicle_type|Fuel Efficiency|Power Perf Factor|Wheelbase|Width|Length|Curb Weight|Fuel Capacity|Latest Launch|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+--------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|      NULL| High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|      NULL| High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300| High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+--------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
only showing top 3 rows

In [28]:
for c in ['Price', 'Year Resale Value']:
    df = df.withColumn(c, regexp_replace(col(c), '[^0-9.-]', '').cast('double'))

df.printSchema()

root
 |-- Manufacturer: string (nullable = true)
 |-- Model: string (nullable = true)
 |-- Unit Sales: integer (nullable = true)
 |-- Price: double (nullable = true)
 |-- Year Resale Value: double (nullable = true)
 |-- Retention %: string (nullable = true)
 |-- Retention Value: string (nullable = true)
 |-- Engine Size: double (nullable = true)
 |-- Horsepower: integer (nullable = true)
 |-- HP Level: string (nullable = true)
 |-- Vehicle_type: string (nullable = true)
 |-- Fuel Efficiency: integer (nullable = true)
 |-- Power Perf Factor: double (nullable = true)
 |-- Wheelbase: double (nullable = true)
 |-- Width: double (nullable = true)
 |-- Length: double (nullable = true)
 |-- Curb Weight: double (nullable = true)
 |-- Fuel Capacity: double (nullable = true)
 |-- Latest Launch: string (nullable = true)

In [29]:
df2 = df.withColumn('Price_Diff', 
                    col('Price') - col('Year Resale Value'))

df2.limit(3).toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch,Price_Diff
0,Mercedes-B,CL500,954,85500.0,63423.0,74%,GOOD,5.0,NaN,High HP,Passenger,20,141.100985,113.6,73.1,196.6,4.115,23.2,4/11/2011,22077.0
1,Mercedes-B,SL-Class,3311,82600.0,58600.0,71%,GOOD,5.0,NaN,High HP,Passenger,20,139.982294,99.0,71.3,177.1,4.125,21.1,3/17/2011,24000.0
2,Porsche,Carrera Cabrio,1866,74970.0,67550.0,90%,GOOD,3.4,300.0,High HP,Passenger,23,135.914710,92.6,69.5,174.5,3.075,17.0,7/11/2011,7420.0

In [30]:
df_reg = df.withColumn('HP Level',regexp_replace(col('HP Level'),"Medium HP","MHP"))\
            .withColumn('HP Level',regexp_replace(col('HP Level'),"High HP","HHP"))

df_reg.limit(20).toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch
0,Mercedes-B,CL500,954,85500.0,63423.0,74%,GOOD,5.0,NaN,HHP,Passenger,20,141.100985,113.6,73.1,196.6,4.115,23.2,4/11/2011
1,Mercedes-B,SL-Class,3311,82600.0,58600.0,71%,GOOD,5.0,NaN,HHP,Passenger,20,139.982294,99.0,71.3,177.1,4.125,21.1,3/17/2011
2,Porsche,Carrera Cabrio,1866,74970.0,67550.0,90%,GOOD,3.4,300.0,HHP,Passenger,23,135.914710,92.6,69.5,174.5,3.075,17.0,7/11/2011
3,Mercedes-B,CL500,954,85500.0,63423.0,74%,GOOD,5.0,302.0,HHP,Passenger,20,141.100985,113.6,73.1,196.6,4.115,23.2,4/11/2011
4,Mercedes-B,SL-Class,3311,82600.0,58600.0,71%,GOOD,5.0,302.0,HHP,Passenger,20,139.982294,99.0,71.3,177.1,4.125,21.1,3/17/2011
5,Porsche,Carrera Cabrio,1866,74970.0,67550.0,90%,GOOD,3.4,300.0,HHP,Passenger,23,135.914710,92.6,69.5,174.5,3.075,17.0,7/11/2011
6,Porsche,Carrera Coupe,1280,71020.0,60625.0,85%,GOOD,3.4,300.0,HHP,Passenger,21,134.390975,92.6,69.5,174.5,3.032,17.0,12/21/2012
7,Dodge,Viper,916,69725.0,58470.0,84%,GOOD,8.0,450.0,HHP,Passenger,16,188.144323,96.2,75.7,176.7,3.375,19.0,8/7/2011
8,Mercedes-B,S-Class,16774,69700.0,50375.0,72%,GOOD,4.3,275.0,MHP,Passenger,21,125.273876,121.5,73.1,203.1,4.133,23.2,6/13/2011
9,Audi,A8,1380,62000.0,39000.0,63%,POOR,4.2,310.0,HHP,Passenger,21,134.656858,113.0,74.0,198.2,3.902,23.7,2/27/2012
10,Lexus,LX470,9126,60105.0,43870.0,73%,GOOD,4.7,230.0,MHP,Car,15,105.760458,112.2,76.4,192.5,5.401,25.4,10/30/2012
11,Chevrolet,Corvette,17947,55705.0,36225.0,65%,POOR,5.7,345.0,HHP,Passenger,22,141.141150,104.5,73.6,179.7,3.210,19.1,5/12/2012
12,Lexus,LS400,6375,54005.0,40375.0,75%,GOOD,4.0,290.0,MHP,Passenger,22,124.446716,112.2,72.0,196.7,3.890,22.5,3/29/2012
13,Toyota,Land Cruiser,9835,51728.0,34080.0,66%,POOR,4.7,230.0,MHP,Car,15,102.528984,112.2,76.4,192.5,5.115,25.4,9/25/2011
14,Mercedes-B,E-Class,27602,49900.0,41450.0,83%,GOOD,3.2,221.0,MHP,Passenger,25,98.249737,111.5,70.8,189.4,3.823,21.1,7/12/2011
15,Lexus,GS400,3334,46305.0,38955.0,84%,GOOD,4.0,300.0,HHP,Passenger,21,125.013357,110.2,70.9,189.2,3.693,19.8,11/28/2012
16,Cadillac,Escalade,14785,46225.0,31245.0,68%,POOR,5.7,255.0,MHP,Car,15,109.509117,117.5,77.0,201.2,5.572,30.0,4/17/2012
17,Volvo,C70,3493,45500.0,34175.0,75%,GOOD,2.3,236.0,MHP,Passenger,23,101.623357,104.9,71.5,185.7,3.601,18.5,4/26/2011
18,Cadillac,Seville,15943,44475.0,27100.0,61%,POOR,4.6,275.0,MHP,Passenger,22,115.621358,112.2,75.0,201.0,3.875,18.5,4/29/2011
19,Lincoln,Town car,48911,43330.0,21725.0,50%,POOR,4.6,215.0,MHP,Passenger,21,93.957917,117.7,78.2,215.3,4.121,19.0,6/4/2012

In [31]:
df.printSchema()

root
 |-- Manufacturer: string (nullable = true)
 |-- Model: string (nullable = true)
 |-- Unit Sales: integer (nullable = true)
 |-- Price: double (nullable = true)
 |-- Year Resale Value: double (nullable = true)
 |-- Retention %: string (nullable = true)
 |-- Retention Value: string (nullable = true)
 |-- Engine Size: double (nullable = true)
 |-- Horsepower: integer (nullable = true)
 |-- HP Level: string (nullable = true)
 |-- Vehicle_type: string (nullable = true)
 |-- Fuel Efficiency: integer (nullable = true)
 |-- Power Perf Factor: double (nullable = true)
 |-- Wheelbase: double (nullable = true)
 |-- Width: double (nullable = true)
 |-- Length: double (nullable = true)
 |-- Curb Weight: double (nullable = true)
 |-- Fuel Capacity: double (nullable = true)
 |-- Latest Launch: string (nullable = true)

### Sort

In [32]:
#df_sort = df.sort(col('Price').desc())

df_sort = df.sort(['Engine Size','Horsepower'], ascending = [0,0])
df_sort.limit(20).toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch
0,Dodge,Viper,916,69725.0,58470.0,84%,GOOD,8.0,450.0,High HP,Passenger,16,188.144323,96.2,75.7,176.7,3.375,19.0,8/7/2011
1,Chevrolet,Corvette,17947,55705.0,36225.0,65%,POOR,5.7,345.0,High HP,Passenger,22,141.141150,104.5,73.6,179.7,3.210,19.1,5/12/2012
2,Cadillac,Escalade,14785,46225.0,31245.0,68%,POOR,5.7,255.0,Medium HP,Car,15,109.509117,117.5,77.0,201.2,5.572,30.0,4/17/2012
3,Lincoln,Navigator,22925,42660.0,20765.0,49%,POOR,5.4,300.0,High HP,Car,15,123.972047,119.0,79.9,204.8,5.393,30.0,12/23/2012
4,Dodge,Durango,101323,26310.0,21436.0,81%,GOOD,5.2,230.0,Medium HP,Car,17,92.854125,115.7,71.7,193.5,4.394,25.0,6/27/2012
5,Dodge,Ram Pickup,227061,19460.0,15060.0,77%,GOOD,5.2,230.0,Medium HP,Car,17,90.211700,138.7,79.3,224.2,4.470,26.0,3/6/2012
6,Mercedes-B,CL500,954,85500.0,63423.0,74%,GOOD,5.0,302.0,High HP,Passenger,20,141.100985,113.6,73.1,196.6,4.115,23.2,4/11/2011
7,Mercedes-B,SL-Class,3311,82600.0,58600.0,71%,GOOD,5.0,302.0,High HP,Passenger,20,139.982294,99.0,71.3,177.1,4.125,21.1,3/17/2011
8,Mercedes-B,CL500,954,85500.0,63423.0,74%,GOOD,5.0,NaN,High HP,Passenger,20,141.100985,113.6,73.1,196.6,4.115,23.2,4/11/2011
9,Mercedes-B,SL-Class,3311,82600.0,58600.0,71%,GOOD,5.0,NaN,High HP,Passenger,20,139.982294,99.0,71.3,177.1,4.125,21.1,3/17/2011
10,Lexus,LX470,9126,60105.0,43870.0,73%,GOOD,4.7,230.0,Medium HP,Car,15,105.760458,112.2,76.4,192.5,5.401,25.4,10/30/2012
11,Toyota,Land Cruiser,9835,51728.0,34080.0,66%,POOR,4.7,230.0,Medium HP,Car,15,102.528984,112.2,76.4,192.5,5.115,25.4,9/25/2011
12,Cadillac,Seville,15943,44475.0,27100.0,61%,POOR,4.6,275.0,Medium HP,Passenger,22,115.621358,112.2,75.0,201.0,3.875,18.5,4/29/2011
13,Cadillac,DeVille,63729,39895.0,22525.0,56%,POOR,4.6,275.0,Medium HP,Passenger,22,113.854598,115.3,74.5,207.2,3.978,18.5,2/23/2012
14,Cadillac,Eldorado,6536,39665.0,25725.0,65%,POOR,4.6,275.0,Medium HP,Passenger,22,113.765874,108.0,75.5,200.6,3.843,19.0,11/27/2011
15,Lincoln,Continental,13798,39080.0,20525.0,53%,POOR,4.6,275.0,Medium HP,Passenger,22,113.540207,109.0,73.6,208.5,3.868,20.0,8/3/2012
16,Ford,Expedition,125338,36135.0,23575.0,65%,POOR,4.6,240.0,Medium HP,Car,16,100.024802,119.0,78.7,204.6,4.808,26.0,9/14/2012
17,Ford,F-Series,540561,26935.0,15075.0,56%,POOR,4.6,220.0,Medium HP,Car,18,89.401935,138.5,79.1,224.5,4.241,25.1,8/16/2012
18,Lincoln,Town car,48911,43330.0,21725.0,50%,POOR,4.6,215.0,Medium HP,Passenger,21,93.957917,117.7,78.2,215.3,4.121,19.0,6/4/2012
19,Mercury,Grand Marquis,81174,22605.0,14875.0,66%,POOR,4.6,200.0,Medium HP,Passenger,21,80.657696,114.7,78.2,212.0,3.958,19.0,7/24/2012

In [33]:
df_dup = df.dropDuplicates()
df_dup.limit(20).toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch
0,Dodge,Intrepid,88028,22505.0,12275.0,55%,POOR,2.7,202,Medium HP,Passenger,22,80.831470,113.0,74.7,203.7,3.489,17.0,6/2/2012
1,Toyota,4Runner,68411,22288.0,19425.0,87%,GOOD,2.7,150,Medium HP,Car,23,62.355577,105.3,66.5,183.3,3.440,18.5,3/7/2011
2,Honda,CR-V,73203,20550.0,17710.0,86%,GOOD,2.0,146,Medium HP,Car,24,60.087967,103.2,68.9,177.6,3.219,15.3,3/21/2012
3,Ford,Taurus,245815,17885.0,10055.0,56%,POOR,3.0,155,Medium HP,Passenger,24,62.503740,108.5,73.0,197.6,3.368,16.0,12/20/2011
4,Chevrolet,Malibu,135126,16535.0,11225.0,68%,POOR,3.1,170,Medium HP,Passenger,25,67.314462,107.0,69.4,190.4,3.051,15.0,3/19/2012
5,Audi,A8,1380,62000.0,39000.0,63%,POOR,4.2,310,High HP,Passenger,21,134.656858,113.0,74.0,198.2,3.902,23.7,2/27/2012
6,Chevrolet,Impala,107995,18890.0,11550.0,61%,POOR,3.4,180,Medium HP,Passenger,27,71.838039,110.5,73.0,200.0,3.389,17.0,6/18/2011
7,Dodge,Viper,916,69725.0,58470.0,84%,GOOD,8.0,450,High HP,Passenger,16,188.144323,96.2,75.7,176.7,3.375,19.0,8/7/2011
8,Buick,Century,91561,21975.0,12475.0,57%,POOR,3.1,175,Medium HP,Passenger,25,71.181451,109.0,72.7,194.6,3.368,17.5,11/2/2011
9,Dodge,Ram Wagon,16767,21315.0,15510.0,73%,GOOD,3.9,175,Medium HP,Car,15,71.135292,109.6,78.8,192.6,4.245,32.0,1/6/2012
10,Lincoln,Continental,13798,39080.0,20525.0,53%,POOR,4.6,275,Medium HP,Passenger,22,113.540207,109.0,73.6,208.5,3.868,20.0,8/3/2012
11,Buick,Park Avenue,27851,31965.0,20190.0,63%,POOR,3.8,205,Medium HP,Passenger,24,85.828408,113.8,74.7,206.8,3.778,18.5,3/23/2012
12,Dodge,Durango,101323,26310.0,21436.0,81%,GOOD,5.2,230,Medium HP,Car,17,92.854125,115.7,71.7,193.5,4.394,25.0,6/27/2012
13,Mercury,Mystique,14351,16240.0,8800.0,54%,POOR,2.0,125,Medium HP,Passenger,28,50.997748,106.5,69.1,184.8,2.769,15.0,12/19/2012
14,Saab,3-Sep,12115,26100.0,18255.0,70%,GOOD,2.0,185,Medium HP,Passenger,23,76.023048,102.6,67.4,182.2,2.990,16.9,6/12/2011
15,Porsche,Carrera Coupe,1280,71020.0,60625.0,85%,GOOD,3.4,300,High HP,Passenger,21,134.390975,92.6,69.5,174.5,3.032,17.0,12/21/2012
16,Toyota,Sienna,65119,22368.0,18689.0,84%,GOOD,3.0,194,Medium HP,Car,22,78.027219,114.2,73.4,193.5,3.759,20.9,10/5/2012
17,Mercedes-B,SLK230,1526,41000.0,28635.0,70%,GOOD,2.3,185,Medium HP,Passenger,27,81.848969,94.5,67.5,157.3,2.975,14.0,8/6/2011
18,BMW,328i,9231,33400.0,28675.0,86%,GOOD,2.8,193,Medium HP,Passenger,24,81.877069,107.3,68.5,176.0,3.197,16.6,1/29/2012
19,Lexus,ES300,24072,31505.0,26975.0,86%,GOOD,3.0,210,Medium HP,Passenger,23,87.211001,105.1,70.5,190.2,3.373,18.5,7/9/2012

In [34]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("data1").getOrCreate()
spark = SparkSession.builder.appName("data2").getOrCreate()

data1 = [
    ('Shiva',1),
    ('Jashvitha',2)
]

schema1 = 'name STRING, id STRING'

df_data1 = spark.createDataFrame(data1,schema1)

data2 = [
    (3,'Dhiyanshi'),
    (4,'Badugu')
]
schema2 = 'id STRING, name STRING'

df_data2 = spark.createDataFrame(data2,schema2)

In [35]:
df_data1.toPandas()
#df_data2.toPandas()

Py4JJavaError: An error occurred while calling o351.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 31.0 failed 1 times, most recent failure: Lost task 0.0 in stage 31.0 (TID 40) (Shivatejabadugu executor driver): java.io.IOException: Cannot run program "python3": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at org.apache.spark.api.python.PythonWorkerFactory.createSimpleWorker(PythonWorkerFactory.scala:247)
	at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:154)
	at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:158)
	at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:309)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:72)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:180)
	at org.apache.spark.scheduler.Task.run(Task.scala:147)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:873)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:86)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:83)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:97)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:876)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:505)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 34 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$3(DAGScheduler.scala:3122)
	at scala.Option.getOrElse(Option.scala:201)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:3122)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:3114)
	at scala.collection.immutable.List.foreach(List.scala:323)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:3114)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1303)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1303)
	at scala.Option.foreach(Option.scala:437)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1303)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3397)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3328)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3317)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:50)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1017)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2496)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2517)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2536)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2561)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1057)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:417)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1056)
	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:462)
	at org.apache.spark.sql.classic.Dataset.$anonfun$collectToPython$1(Dataset.scala:2085)
	at org.apache.spark.sql.classic.Dataset.$anonfun$withAction$2(Dataset.scala:2265)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:717)
	at org.apache.spark.sql.classic.Dataset.$anonfun$withAction$1(Dataset.scala:2263)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$8(SQLExecution.scala:177)
	at org.apache.spark.sql.execution.SQLExecution$.withSessionTagsApplied(SQLExecution.scala:285)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$7(SQLExecution.scala:139)
	at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:94)
	at org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:112)
	at org.apache.spark.sql.artifact.ArtifactManager.withClassLoaderIfNeeded(ArtifactManager.scala:106)
	at org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:111)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$6(SQLExecution.scala:139)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:308)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$1(SQLExecution.scala:138)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId0(SQLExecution.scala:92)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:250)
	at org.apache.spark.sql.classic.Dataset.withAction(Dataset.scala:2263)
	at org.apache.spark.sql.classic.Dataset.collectToPython(Dataset.scala:2081)
	at jdk.internal.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:184)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:108)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Cannot run program "python3": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at org.apache.spark.api.python.PythonWorkerFactory.createSimpleWorker(PythonWorkerFactory.scala:247)
	at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:154)
	at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:158)
	at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:309)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:72)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:374)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:338)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:180)
	at org.apache.spark.scheduler.Task.run(Task.scala:147)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:873)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:86)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:83)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:97)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:876)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:505)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 34 more

In [ ]:
#df_data1.union(df_data2).toPandas()
df_data1.unionByName(df_data2).toPandas()

        name id
0      Shiva  1
1  Jashvitha  2
2  Dhiyanshi  3
3     Badugu  4

In [ ]:
df.limit(5).toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch
0,Mercedes-B,CL500,954,85500.0,63423.0,74%,GOOD,5.0,NaN,High HP,Passenger,20,141.100985,113.6,73.1,196.6,4.115,23.2,4/11/2011
1,Mercedes-B,SL-Class,3311,82600.0,58600.0,71%,GOOD,5.0,NaN,High HP,Passenger,20,139.982294,99.0,71.3,177.1,4.125,21.1,3/17/2011
2,Porsche,Carrera Cabrio,1866,74970.0,67550.0,90%,GOOD,3.4,300.0,High HP,Passenger,23,135.914710,92.6,69.5,174.5,3.075,17.0,7/11/2011
3,Mercedes-B,CL500,954,85500.0,63423.0,74%,GOOD,5.0,302.0,High HP,Passenger,20,141.100985,113.6,73.1,196.6,4.115,23.2,4/11/2011
4,Mercedes-B,SL-Class,3311,82600.0,58600.0,71%,GOOD,5.0,302.0,High HP,Passenger,20,139.982294,99.0,71.3,177.1,4.125,21.1,3/17/2011

In [ ]:
df_upper = df.select(upper('Manufacturer').alias('UpperCase_Manufacturer'))

df_upper.limit(10).toPandas()

  UpperCase_Manufacturer
0             MERCEDES-B
1             MERCEDES-B
2                PORSCHE
3             MERCEDES-B
4             MERCEDES-B
5                PORSCHE
6                PORSCHE
7                  DODGE
8             MERCEDES-B
9                   AUDI

### DateFormat

In [ ]:
#df = df.withColumn('curr_date',current_date())

#df = df.withColumn('7DaysAfter',date_add('curr_date',7))
df = df.withColumn('7DaysBefore',date_add('curr_date',-7))
df.limit(3).toPandas()

{"ts": "2026-10-14 14:09:16.217", "level": "ERROR", "logger": "DataFrameQueryContextLogger", "msg": "[UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `curr_date` cannot be resolved. Did you mean one of the following? [`Model`, `Price`, `Width`, `Length`, `Wheelbase`]. SQLSTATE: 42703", "context": {"file": "jdk.internal.reflect.GeneratedMethodAccessor72.invoke(Unknown Source)", "line": "", "fragment": "col", "errorClass": "UNRESOLVED_COLUMN.WITH_SUGGESTION"}, "exception": {"class": "Py4JJavaError", "msg": "An error occurred while calling o179.withColumn.\n: org.apache.spark.sql.AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `curr_date` cannot be resolved. Did you mean one of the following? [`Model`, `Price`, `Width`, `Length`, `Wheelbase`]. SQLSTATE: 42703;\n'Project [Manufacturer#22, Model#23, Unit Sales#24, Price#335, Year Resale Value#336, Retention %#27, Retention Value#28, Engine Size#29, Horsepower#30, HP Level#31, Vehicle_type#32, Fuel Efficiency#33, Power Perf Factor#34, Wheelbase#35, Width#36, Length#37, Curb Weight#38, Fuel Capacity#39, Latest Launch#40, 'date_add('curr_date, -7) AS 7DaysBefore#441]\n+- Project [Manufacturer#22, Model#23, Unit Sales#24, Price#335, cast(regexp_replace(Year Resale Value#26, [^0-9.-], , 1) as double) AS Year Resale Value#336, Retention %#27, Retention Value#28, Engine Size#29, Horsepower#30, HP Level#31, Vehicle_type#32, Fuel Efficiency#33, Power Perf Factor#34, Wheelbase#35, Width#36, Length#37, Curb Weight#38, Fuel Capacity#39, Latest Launch#40]\n   +- Project [Manufacturer#22, Model#23, Unit Sales#24, cast(regexp_replace(Price#25, [^0-9.-], , 1) as double) AS Price#335, Year Resale Value#26, Retention %#27, Retention Value#28, Engine Size#29, Horsepower#30, HP Level#31, Vehicle_type#32, Fuel Efficiency#33, Power Perf Factor#34, Wheelbase#35, Width#36, Length#37, Curb Weight#38, Fuel Capacity#39, Latest Launch#40]\n      +- Relation [Manufacturer#22,Model#23,Unit Sales#24,Price#25,Year Resale Value#26,Retention %#27,Retention Value#28,Engine Size#29,Horsepower#30,HP Level#31,Vehicle_type#32,Fuel Efficiency#33,Power Perf Factor#34,Wheelbase#35,Width#36,Length#37,Curb Weight#38,Fuel Capacity#39,Latest Launch#40] csv\n\r\n\tat org.apache.spark.sql.errors.QueryCompilationErrors$.unresolvedAttributeError(QueryCompilationErrors.scala:430)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.org$apache$spark$sql$catalyst$analysis$CheckAnalysis$$failUnresolvedAttribute(CheckAnalysis.scala:166)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7(CheckAnalysis.scala:406)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7$adapted(CheckAnalysis.scala:404)\r\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:273)\r\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:272)\r\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:272)\r\n\tat scala.collection.IterableOnceOps.foreach(IterableOnce.scala:630)\r\n\tat scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:628)\r\n\tat scala.collection.AbstractIterable.foreach(Iterable.scala:936)\r\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:272)\r\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:272)\r\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:272)\r\n\tat scala.collection.immutable.Vector.foreach(Vector.scala:2125)\r\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:272)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$6(CheckAnalysis.scala:404)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$6$adapted(CheckAnalysis.scala:404)\r\n\tat scala.collection.immutable.List.foreach(List.scala:323)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2(CheckAnalysis.scala:404)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2$adapted(CheckAnalysis.scala:281)\r\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:273)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0(CheckAnalysis.scala:281)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0$(CheckAnalysis.scala:252)\r\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis0(Analyzer.scala:289)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:241)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:228)\r\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:289)\r\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$resolveInFixedPoint$1(HybridAnalyzer.scala:238)\r\n\tat scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)\r\n\tat org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:89)\r\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.resolveInFixedPoint(HybridAnalyzer.scala:238)\r\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$apply$1(HybridAnalyzer.scala:91)\r\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.withTrackedAnalyzerBridgeState(HybridAnalyzer.scala:122)\r\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.apply(HybridAnalyzer.scala:84)\r\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:322)\r\n\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:423)\r\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:322)\r\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$2(QueryExecution.scala:139)\r\n\tat org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:148)\r\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:330)\r\n\tat org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:717)\r\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:330)\r\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)\r\n\tat org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:329)\r\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$1(QueryExecution.scala:139)\r\n\tat scala.util.Try$.apply(Try.scala:217)\r\n\tat org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1392)\r\n\tat org.apache.spark.util.Utils$.getTryWithCallerStacktrace(Utils.scala:1453)\r\n\tat org.apache.spark.util.LazyTry.get(LazyTry.scala:58)\r\n\tat org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:150)\r\n\tat org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:90)\r\n\tat org.apache.spark.sql.classic.Dataset$.$anonfun$ofRows$1(Dataset.scala:114)\r\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)\r\n\tat org.apache.spark.sql.classic.Dataset$.ofRows(Dataset.scala:112)\r\n\tat org.apache.spark.sql.classic.Dataset.withPlan(Dataset.scala:2306)\r\n\tat org.apache.spark.sql.classic.Dataset.withColumns(Dataset.scala:1305)\r\n\tat org.apache.spark.sql.classic.Dataset.withColumns(Dataset.scala:231)\r\n\tat org.apache.spark.sql.Dataset.withColumn(Dataset.scala:2191)\r\n\tat org.apache.spark.sql.classic.Dataset.withColumn(Dataset.scala:1844)\r\n\tat org.apache.spark.sql.classic.Dataset.withColumn(Dataset.scala:231)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:569)\r\n\tat py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)\r\n\tat py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)\r\n\tat py4j.Gateway.invoke(Gateway.java:282)\r\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\r\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\r\n\tat py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:184)\r\n\tat py4j.ClientServerConnection.run(ClientServerConnection.java:108)\r\n\tat java.base/java.lang.Thread.run(Thread.java:840)\r\n\tSuppressed: org.apache.spark.util.Utils$OriginalTryStackTraceException: Full stacktrace of original doTryWithCallerStacktrace caller\r\n\t\tat org.apache.spark.sql.errors.QueryCompilationErrors$.unresolvedAttributeError(QueryCompilationErrors.scala:430)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.org$apache$spark$sql$catalyst$analysis$CheckAnalysis$$failUnresolvedAttribute(CheckAnalysis.scala:166)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7(CheckAnalysis.scala:406)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7$adapted(CheckAnalysis.scala:404)\r\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:273)\r\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:272)\r\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:272)\r\n\t\tat scala.collection.IterableOnceOps.foreach(IterableOnce.scala:630)\r\n\t\tat scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:628)\r\n\t\tat scala.collection.AbstractIterable.foreach(Iterable.scala:936)\r\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:272)\r\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:272)\r\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:272)\r\n\t\tat scala.collection.immutable.Vector.foreach(Vector.scala:2125)\r\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:272)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$6(CheckAnalysis.scala:404)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$6$adapted(CheckAnalysis.scala:404)\r\n\t\tat scala.collection.immutable.List.foreach(List.scala:323)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2(CheckAnalysis.scala:404)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2$adapted(CheckAnalysis.scala:281)\r\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:273)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0(CheckAnalysis.scala:281)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0$(CheckAnalysis.scala:252)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis0(Analyzer.scala:289)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:241)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:228)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:289)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$resolveInFixedPoint$1(HybridAnalyzer.scala:238)\r\n\t\tat scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)\r\n\t\tat org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:89)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.resolveInFixedPoint(HybridAnalyzer.scala:238)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$apply$1(HybridAnalyzer.scala:91)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.withTrackedAnalyzerBridgeState(HybridAnalyzer.scala:122)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.apply(HybridAnalyzer.scala:84)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:322)\r\n\t\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:423)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:322)\r\n\t\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$2(QueryExecution.scala:139)\r\n\t\tat org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:148)\r\n\t\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:330)\r\n\t\tat org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:717)\r\n\t\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:330)\r\n\t\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)\r\n\t\tat org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:329)\r\n\t\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$1(QueryExecution.scala:139)\r\n\t\tat scala.util.Try$.apply(Try.scala:217)\r\n\t\tat org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1392)\r\n\t\tat org.apache.spark.util.LazyTry.tryT$lzycompute(LazyTry.scala:46)\r\n\t\tat org.apache.spark.util.LazyTry.tryT(LazyTry.scala:46)\r\n\t\t... 24 more\r\n", "stacktrace": [{"class": null, "method": "deco", "file": "c:\\Users\\shiva\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pyspark\\errors\\exceptions\\captured.py", "line": "263"}, {"class": null, "method": "get_return_value", "file": "c:\\Users\\shiva\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\py4j\\protocol.py", "line": "327"}]}}

AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `curr_date` cannot be resolved. Did you mean one of the following? [`Model`, `Price`, `Width`, `Length`, `Wheelbase`]. SQLSTATE: 42703;
'Project [Manufacturer#22, Model#23, Unit Sales#24, Price#335, Year Resale Value#336, Retention %#27, Retention Value#28, Engine Size#29, Horsepower#30, HP Level#31, Vehicle_type#32, Fuel Efficiency#33, Power Perf Factor#34, Wheelbase#35, Width#36, Length#37, Curb Weight#38, Fuel Capacity#39, Latest Launch#40, 'date_add('curr_date, -7) AS 7DaysBefore#441]
+- Project [Manufacturer#22, Model#23, Unit Sales#24, Price#335, cast(regexp_replace(Year Resale Value#26, [^0-9.-], , 1) as double) AS Year Resale Value#336, Retention %#27, Retention Value#28, Engine Size#29, Horsepower#30, HP Level#31, Vehicle_type#32, Fuel Efficiency#33, Power Perf Factor#34, Wheelbase#35, Width#36, Length#37, Curb Weight#38, Fuel Capacity#39, Latest Launch#40]
   +- Project [Manufacturer#22, Model#23, Unit Sales#24, cast(regexp_replace(Price#25, [^0-9.-], , 1) as double) AS Price#335, Year Resale Value#26, Retention %#27, Retention Value#28, Engine Size#29, Horsepower#30, HP Level#31, Vehicle_type#32, Fuel Efficiency#33, Power Perf Factor#34, Wheelbase#35, Width#36, Length#37, Curb Weight#38, Fuel Capacity#39, Latest Launch#40]
      +- Relation [Manufacturer#22,Model#23,Unit Sales#24,Price#25,Year Resale Value#26,Retention %#27,Retention Value#28,Engine Size#29,Horsepower#30,HP Level#31,Vehicle_type#32,Fuel Efficiency#33,Power Perf Factor#34,Wheelbase#35,Width#36,Length#37,Curb Weight#38,Fuel Capacity#39,Latest Launch#40] csv

In [ ]:
df_dates = df.withColumn('curr_date', current_date()) \
             .withColumn('7DaysAfter', date_add('curr_date', 7)) \
             .withColumn('diffdate', datediff('7DaysAfter', 'curr_date')) \
             .withColumn('curr_date', date_format('curr_date', 'dd-MM-yyyy')) \
             .withColumn('7DaysAfter', date_format('7DaysAfter', 'dd-MM-yyyy')) \
             .select('Manufacturer', 'Model', 'curr_date', '7DaysAfter', 'diffdate')

df_dates.limit(3).toPandas()

  Manufacturer           Model   curr_date  7DaysAfter  diffdate
0   Mercedes-B           CL500  11-10-2026  18-10-2026         7
1   Mercedes-B        SL-Class  11-10-2026  18-10-2026         7
2      Porsche  Carrera Cabrio  11-10-2026  18-10-2026         7

### Handling Nulls values
## Dropping Nulls

In [ ]:
df_null = df.dropna('any')

df_null.limit(5).toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch
0,Porsche,Carrera Cabrio,1866,"$74,970","$67,550",90%,GOOD,3.4,300,High HP,Passenger,23,135.914710,92.6,69.5,174.5,3.075,17.0,7/11/2011
1,Mercedes-B,CL500,954,"$85,500","$63,423",74%,GOOD,5.0,302,High HP,Passenger,20,141.100985,113.6,73.1,196.6,4.115,23.2,4/11/2011
2,Mercedes-B,SL-Class,3311,"$82,600","$58,600",71%,GOOD,5.0,302,High HP,Passenger,20,139.982294,99.0,71.3,177.1,4.125,21.1,3/17/2011
3,Porsche,Carrera Cabrio,1866,"$74,970","$67,550",90%,GOOD,3.4,300,High HP,Passenger,23,135.914710,92.6,69.5,174.5,3.075,17.0,7/11/2011
4,Porsche,Carrera Coupe,1280,"$71,020","$60,625",85%,GOOD,3.4,300,High HP,Passenger,21,134.390975,92.6,69.5,174.5,3.032,17.0,12/21/2012

In [ ]:
df.dropna('any')                              # drop rows with a null in ANY column (the default)
df.dropna(subset=['Horsepower'])              # drop rows only if Horsepower is null
df.dropna(thresh=15)                          # keep rows with at least 15 non-null values

DataFrame[Manufacturer: string, Model: string, Unit Sales: int, Price: string, Year Resale Value: string, Retention %: string, Retention Value: string, Engine Size: double, Horsepower: int, HP Level: string, Vehicle_type: string, Fuel Efficiency: int, Power Perf Factor: double, Wheelbase: double, Width: double, Length: double, Curb Weight: double, Fuel Capacity: double, Latest Launch: string]

In [ ]:
df.show()
print(df.count(), df_null.count())

+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|Manufacturer|         Model|Unit Sales|   Price|Year Resale Value|Retention %|Retention Value|Engine Size|Horsepower| HP Level|Vehicle_type|Fuel Efficiency|Power Perf Factor|Wheelbase|Width|Length|Curb Weight|Fuel Capacity|Latest Launch|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|      NULL|  High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|      NULL|  High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300|  High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300|  High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
|     Porsche| Carrera Coupe|      1280|$71,020 |         $60,625 |        85%|           GOOD|        3.4|       300|  High HP|   Passenger|             21|      134.3909754|     92.6| 69.5| 174.5|      3.032|         17.0|   12/21/2012|
|       Dodge|         Viper|       916|$69,725 |         $58,470 |        84%|           GOOD|        8.0|       450|  High HP|   Passenger|             16|       188.144323|     96.2| 75.7| 176.7|      3.375|         19.0|     8/7/2011|
|  Mercedes-B|       S-Class|     16774|$69,700 |         $50,375 |        72%|           GOOD|        4.3|       275|Medium HP|   Passenger|             21|      125.2738757|    121.5| 73.1| 203.1|      4.133|         23.2|    6/13/2011|
|        Audi|            A8|      1380|$62,000 |         $39,000 |        63%|           POOR|        4.2|       310|  High HP|   Passenger|             21|      134.6568582|    113.0| 74.0| 198.2|      3.902|         23.7|    2/27/2012|
|       Lexus|         LX470|      9126|$60,105 |         $43,870 |        73%|           GOOD|        4.7|       230|Medium HP|         Car|             15|       105.760458|    112.2| 76.4| 192.5|      5.401|         25.4|   10/30/2012|
|   Chevrolet|      Corvette|     17947|$55,705 |         $36,225 |        65%|           POOR|        5.7|       345|  High HP|   Passenger|             22|        141.14115|    104.5| 73.6| 179.7|       3.21|         19.1|    5/12/2012|
|       Lexus|         LS400|      6375|$54,005 |         $40,375 |        75%|           GOOD|        4.0|       290|Medium HP|   Passenger|             22|      124.4467163|    112.2| 72.0| 196.7|       3.89|         22.5|    3/29/2012|
|      Toyota|  Land Cruiser|      9835|$51,728 |         $34,080 |        66%|           POOR|        4.7|       230|Medium HP|         Car|             15|      102.5289842|    112.2| 76.4| 192.5|      5.115|         25.4|    9/25/2011|
|  Mercedes-B|       E-Class|     27602|$49,900 |         $41,450 |        83%|           GOOD|        3.2|       221|Medium HP|   Passenger|             25|       98.2497375|    111.5| 70.8| 189.4|      3.823|         21.1|    7/12/2011|
|       Lexus|         GS400|      3334|$46,305 |         $38,955 |        84%|           GOOD|        4.0|       300|  High HP|   Passenger|             21|      125.0133574|    110.2| 70.9| 189.2|      3.693|         19.8|   11/28/2012|
|    Cadillac|      Escalade|     14785|$46,225 |         $31,245 |        68%|           POOR|        5.7|       255|Medium HP|         Car|             15|      109.5091165|    117.5| 77.0| 201.2|      5.572|         30.0|    4/17/2012|
|       Volvo|           C70|      3493|$45,500 |         $34,175 |        75%|           GOOD|        2.3|       236|Medium HP|   Passenger|             23|      101.6233572|    104.9| 71.5| 185.7|      3.601|         18.5|    4/26/2011|
|    Cadillac|       Seville|     15943|$44,475 |         $27,100 |        61%|           POOR|        4.6|       275|Medium HP|   Passenger|             22|      115.6213578|    112.2| 75.0| 201.0|      3.875|         18.5|    4/29/2011|
|     Lincoln|      Town car|     48911|$43,330 |         $21,725 |        50%|           POOR|        4.6|       215|Medium HP|   Passenger|             21|       93.9579169|    117.7| 78.2| 215.3|      4.121|         19.0|     6/4/2012|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
only showing top 20 rows
158 152

### Replace nullvalues

In [ ]:
df.fillna(0, subset=['Horsepower'])\
    .filter(col('Horsepower') == 0)\
    .select('Manufacturer', 'Model', 'Horsepower') \
    .show()

+------------+--------+----------+
|Manufacturer|   Model|Horsepower|
+------------+--------+----------+
|  Mercedes-B|   CL500|         0|
|  Mercedes-B|SL-Class|         0|
|         BMW|    528i|         0|
|       Acura| Integra|         0|
|       Dodge| Ram Van|         0|
|       Dodge|  Dakota|         0|
+------------+--------+----------+

In [ ]:
df.show()

+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|Manufacturer|         Model|Unit Sales|   Price|Year Resale Value|Retention %|Retention Value|Engine Size|Horsepower| HP Level|Vehicle_type|Fuel Efficiency|Power Perf Factor|Wheelbase|Width|Length|Curb Weight|Fuel Capacity|Latest Launch|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|      NULL|  High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|      NULL|  High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300|  High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300|  High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
|     Porsche| Carrera Coupe|      1280|$71,020 |         $60,625 |        85%|           GOOD|        3.4|       300|  High HP|   Passenger|             21|      134.3909754|     92.6| 69.5| 174.5|      3.032|         17.0|   12/21/2012|
|       Dodge|         Viper|       916|$69,725 |         $58,470 |        84%|           GOOD|        8.0|       450|  High HP|   Passenger|             16|       188.144323|     96.2| 75.7| 176.7|      3.375|         19.0|     8/7/2011|
|  Mercedes-B|       S-Class|     16774|$69,700 |         $50,375 |        72%|           GOOD|        4.3|       275|Medium HP|   Passenger|             21|      125.2738757|    121.5| 73.1| 203.1|      4.133|         23.2|    6/13/2011|
|        Audi|            A8|      1380|$62,000 |         $39,000 |        63%|           POOR|        4.2|       310|  High HP|   Passenger|             21|      134.6568582|    113.0| 74.0| 198.2|      3.902|         23.7|    2/27/2012|
|       Lexus|         LX470|      9126|$60,105 |         $43,870 |        73%|           GOOD|        4.7|       230|Medium HP|         Car|             15|       105.760458|    112.2| 76.4| 192.5|      5.401|         25.4|   10/30/2012|
|   Chevrolet|      Corvette|     17947|$55,705 |         $36,225 |        65%|           POOR|        5.7|       345|  High HP|   Passenger|             22|        141.14115|    104.5| 73.6| 179.7|       3.21|         19.1|    5/12/2012|
|       Lexus|         LS400|      6375|$54,005 |         $40,375 |        75%|           GOOD|        4.0|       290|Medium HP|   Passenger|             22|      124.4467163|    112.2| 72.0| 196.7|       3.89|         22.5|    3/29/2012|
|      Toyota|  Land Cruiser|      9835|$51,728 |         $34,080 |        66%|           POOR|        4.7|       230|Medium HP|         Car|             15|      102.5289842|    112.2| 76.4| 192.5|      5.115|         25.4|    9/25/2011|
|  Mercedes-B|       E-Class|     27602|$49,900 |         $41,450 |        83%|           GOOD|        3.2|       221|Medium HP|   Passenger|             25|       98.2497375|    111.5| 70.8| 189.4|      3.823|         21.1|    7/12/2011|
|       Lexus|         GS400|      3334|$46,305 |         $38,955 |        84%|           GOOD|        4.0|       300|  High HP|   Passenger|             21|      125.0133574|    110.2| 70.9| 189.2|      3.693|         19.8|   11/28/2012|
|    Cadillac|      Escalade|     14785|$46,225 |         $31,245 |        68%|           POOR|        5.7|       255|Medium HP|         Car|             15|      109.5091165|    117.5| 77.0| 201.2|      5.572|         30.0|    4/17/2012|
|       Volvo|           C70|      3493|$45,500 |         $34,175 |        75%|           GOOD|        2.3|       236|Medium HP|   Passenger|             23|      101.6233572|    104.9| 71.5| 185.7|      3.601|         18.5|    4/26/2011|
|    Cadillac|       Seville|     15943|$44,475 |         $27,100 |        61%|           POOR|        4.6|       275|Medium HP|   Passenger|             22|      115.6213578|    112.2| 75.0| 201.0|      3.875|         18.5|    4/29/2011|
|     Lincoln|      Town car|     48911|$43,330 |         $21,725 |        50%|           POOR|        4.6|       215|Medium HP|   Passenger|             21|       93.9579169|    117.7| 78.2| 215.3|      4.121|         19.0|     6/4/2012|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
only showing top 20 rows

In [51]:
df_clean = df
for c in ['Price', 'Year Resale Value']:
    df_clean = df_clean.withColumn(c, regexp_replace(col(c), '[^0-9.-]', '').cast('double'))

df_clean.printSchema()

root
 |-- Manufacturer: string (nullable = true)
 |-- Model: string (nullable = true)
 |-- Unit Sales: integer (nullable = true)
 |-- Price: double (nullable = true)
 |-- Year Resale Value: double (nullable = true)
 |-- Retention %: string (nullable = true)
 |-- Retention Value: string (nullable = true)
 |-- Engine Size: double (nullable = true)
 |-- Horsepower: integer (nullable = true)
 |-- HP Level: string (nullable = true)
 |-- Vehicle_type: string (nullable = true)
 |-- Fuel Efficiency: integer (nullable = true)
 |-- Power Perf Factor: double (nullable = true)
 |-- Wheelbase: double (nullable = true)
 |-- Width: double (nullable = true)
 |-- Length: double (nullable = true)
 |-- Curb Weight: double (nullable = true)
 |-- Fuel Capacity: double (nullable = true)
 |-- Latest Launch: string (nullable = true)

In [52]:
df_when1 = df_clean.withColumn('flag',
                 when (col('Year Resale Value')>50000,'Super good')
                .when((col('Year Resale Value') >= 40000) & (col('Year Resale Value') <= 50000), 'Good to buy')
                .when((col('Year Resale Value') >= 30000) & (col('Year Resale Value') < 40000), 'Average')
                .otherwise('Not Good to Buy')) \
                .withColumn('Depreciation',col('Price') - col('Year Resale Value'))\
                .select('Manufacturer', 'Model', 'Price', 'Year Resale Value','Depreciation', 'flag')

df_when1.show()

+------------+--------------+-------+-----------------+------------+---------------+
|Manufacturer|         Model|  Price|Year Resale Value|Depreciation|           flag|
+------------+--------------+-------+-----------------+------------+---------------+
|  Mercedes-B|         CL500|85500.0|          63423.0|     22077.0|     Super good|
|  Mercedes-B|      SL-Class|82600.0|          58600.0|     24000.0|     Super good|
|     Porsche|Carrera Cabrio|74970.0|          67550.0|      7420.0|     Super good|
|  Mercedes-B|         CL500|85500.0|          63423.0|     22077.0|     Super good|
|  Mercedes-B|      SL-Class|82600.0|          58600.0|     24000.0|     Super good|
|     Porsche|Carrera Cabrio|74970.0|          67550.0|      7420.0|     Super good|
|     Porsche| Carrera Coupe|71020.0|          60625.0|     10395.0|     Super good|
|       Dodge|         Viper|69725.0|          58470.0|     11255.0|     Super good|
|  Mercedes-B|       S-Class|69700.0|          50375.0|     19325.0|     Super good|
|        Audi|            A8|62000.0|          39000.0|     23000.0|        Average|
|       Lexus|         LX470|60105.0|          43870.0|     16235.0|    Good to buy|
|   Chevrolet|      Corvette|55705.0|          36225.0|     19480.0|        Average|
|       Lexus|         LS400|54005.0|          40375.0|     13630.0|    Good to buy|
|      Toyota|  Land Cruiser|51728.0|          34080.0|     17648.0|        Average|
|  Mercedes-B|       E-Class|49900.0|          41450.0|      8450.0|    Good to buy|
|       Lexus|         GS400|46305.0|          38955.0|      7350.0|        Average|
|    Cadillac|      Escalade|46225.0|          31245.0|     14980.0|        Average|
|       Volvo|           C70|45500.0|          34175.0|     11325.0|        Average|
|    Cadillac|       Seville|44475.0|          27100.0|     17375.0|Not Good to Buy|
|     Lincoln|      Town car|43330.0|          21725.0|     21605.0|Not Good to Buy|
+------------+--------------+-------+-----------------+------------+---------------+
only showing top 20 rows

In [53]:
df_clean.groupBy('Manufacturer') \
        .agg(avg('Price').alias('Total_Price')) \
        .orderBy(col('Total_Price').desc()) \
        .show()

+------------+------------------+
|Manufacturer|       Total_Price|
+------------+------------------+
|     Porsche|           65597.5|
|  Mercedes-B| 58577.27272727273|
|       Lexus|           44055.0|
|      Jaguar|           42800.0|
|     Lincoln|           41690.0|
|    Cadillac|           40254.0|
|        Audi|           39980.0|
|         BMW|33096.666666666664|
|       Volvo|30933.333333333332|
|       Acura|30633.333333333332|
|        Saab|           29610.0|
|    Infiniti|           29465.0|
|       Buick|          26781.25|
|  Oldsmobile|25622.833333333332|
|       Dodge|24213.636363636364|
|    Chrysler|23430.833333333332|
|     Pontiac|22949.166666666668|
|    Plymouth|           22642.5|
|      Nissan|22360.714285714286|
|  Mitsubishi|22167.428571428572|
+------------+------------------+
only showing top 20 rows

In [54]:
df_When = df.withColumn('Fav', when(col('Manufacturer') == 'Mercedes-B', 'like')\
            .when(col('Manufacturer')== 'Volvo','like')\
            .when(col('Manufacturer')== 'Porsche','Maybe')
            .otherwise('Dislike')) \
            .select('Manufacturer', 'Model', 'Horsepower', 'Fav')

df_When.limit(20).toPandas()

   Manufacturer           Model  Horsepower      Fav
0    Mercedes-B           CL500         NaN     like
1    Mercedes-B        SL-Class         NaN     like
2       Porsche  Carrera Cabrio       300.0    Maybe
3    Mercedes-B           CL500       302.0     like
4    Mercedes-B        SL-Class       302.0     like
5       Porsche  Carrera Cabrio       300.0    Maybe
6       Porsche   Carrera Coupe       300.0    Maybe
7         Dodge           Viper       450.0  Dislike
8    Mercedes-B         S-Class       275.0     like
9          Audi              A8       310.0  Dislike
10        Lexus           LX470       230.0  Dislike
11    Chevrolet        Corvette       345.0  Dislike
12        Lexus           LS400       290.0  Dislike
13       Toyota    Land Cruiser       230.0  Dislike
14   Mercedes-B         E-Class       221.0     like
15        Lexus           GS400       300.0  Dislike
16     Cadillac        Escalade       255.0  Dislike
17        Volvo             C70       236.0     like
18     Cadillac         Seville       275.0  Dislike
19      Lincoln        Town car       215.0  Dislike

In [55]:
fav1 = when(col('Manufacturer') == 'Mercedes-B', 'like')\
            .when(col('Manufacturer')== 'Volvo','like')\
            .when(col('Manufacturer')== 'Porsche','Maybe')\
            .otherwise('Dislike')
            
df_when2 = df.withColumn('fav1', fav1)\
             .select('Manufacturer', 'Model', 'Horsepower', 'Fav1')
             

df_when2.limit(20).toPandas()

   Manufacturer           Model  Horsepower     Fav1
0    Mercedes-B           CL500         NaN     like
1    Mercedes-B        SL-Class         NaN     like
2       Porsche  Carrera Cabrio       300.0    Maybe
3    Mercedes-B           CL500       302.0     like
4    Mercedes-B        SL-Class       302.0     like
5       Porsche  Carrera Cabrio       300.0    Maybe
6       Porsche   Carrera Coupe       300.0    Maybe
7         Dodge           Viper       450.0  Dislike
8    Mercedes-B         S-Class       275.0     like
9          Audi              A8       310.0  Dislike
10        Lexus           LX470       230.0  Dislike
11    Chevrolet        Corvette       345.0  Dislike
12        Lexus           LS400       290.0  Dislike
13       Toyota    Land Cruiser       230.0  Dislike
14   Mercedes-B         E-Class       221.0     like
15        Lexus           GS400       300.0  Dislike
16     Cadillac        Escalade       255.0  Dislike
17        Volvo             C70       236.0     like
18     Cadillac         Seville       275.0  Dislike
19      Lincoln        Town car       215.0  Dislike

In [56]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("data_frame1").getOrCreate()
spark = SparkSession.builder.appName("data_frame2").getOrCreate()

data3 = [
    (1,'gaur','d01'),
    (2,'kit','d02'),
    (3,'sam','d03'),
    (4,'tim','d03'),
    (5,'aman','d05')
]

schema3 = 'id INT, Name STRING, Dept_id STRING'

df_data3 = spark.createDataFrame(data3,schema3)

data4 = [
    ('d01', 'HR'),
    ('d02', 'Marketing'),
    ('d03', 'Accounts'),
    ('d04', 'IT'),
    ('d05', 'Finance')
]

schema4 = 'Dept_id STRING, Department STRING'

df_data4 = spark.createDataFrame(data4,schema4)

In [57]:
import os, sys
os.environ['PYSPARK_PYTHON'] = sys.executable
os.environ['PYSPARK_DRIVER_PYTHON'] = sys.executable

from pyspark.sql import SparkSession
spark = (SparkSession.builder
         .appName("data_frame1")
         .config("spark.pyspark.python", sys.executable)
         .getOrCreate())

In [58]:
import os, sys
os.environ['PYSPARK_PYTHON'] = sys.executable
os.environ['PYSPARK_DRIVER_PYTHON'] = sys.executable

from pyspark.sql import SparkSession
SparkSession.builder.getOrCreate().stop()   # kill whatever session exists

spark = (SparkSession.builder
         .appName("joins")
         .config("spark.pyspark.python", sys.executable)
         .getOrCreate())

print(spark.sparkContext.pythonExec)

c:\Users\shiva\AppData\Local\Programs\Python\Python312\python.exe

In [59]:
data3 = [(1,'gaur','d01'), (2,'kit','d02'), (3,'sam','d03'), (4,'tim','d03'), (5,'aman','d05'),(6,'shiva','d06')]
df_data3 = spark.createDataFrame(data3, 'id INT, Name STRING, Dept_id STRING')

data4 = [('d01','HR'), ('d02','Marketing'), ('d03','Accounts'), ('d04','IT'), ('d05','Finance')]
df_data4 = spark.createDataFrame(data4, 'Dept_id STRING, Department STRING')

df_data3.join(df_data4, on='Dept_id', how='inner').toPandas()

  Dept_id  id  Name Department
0     d01   1  gaur         HR
1     d02   2   kit  Marketing
2     d03   3   sam   Accounts
3     d03   4   tim   Accounts
4     d05   5  aman    Finance

### Left Join

In [ ]:
df_data3.join(df_data4, on='Dept_id', how='left').toPandas()

  Dept_id  id   Name Department
0     d01   1   gaur         HR
1     d02   2    kit  Marketing
2     d03   3    sam   Accounts
3     d03   4    tim   Accounts
4     d05   5   aman    Finance
5     d06   6  shiva        NaN

In [42]:
from pyspark.sql.window import Window

In [43]:
df_rank = df.withColumn('Rank',rank().over(Window.orderBy('Price')))\
            .withColumn('denserank',dense_rank().over(Window.orderBy('Price')))
            
df_rank.limit(30).toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,...,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch,Rank,denserank
0,Saturn,SL,80620,"$10,685","$9,200",86%,GOOD,1.9,100,Medium HP,...,33,39.986425,102.4,66.4,176.9,2.332,12.1,8/16/2012,1,1
1,Toyota,Tacoma,84087,"$11,528","$9,575",83%,GOOD,2.4,142,Medium HP,...,23,55.297117,103.3,66.5,178.7,2.580,15.1,8/1/2011,2,2
2,Hyundai,Elantra,66692,"$11,799","$7,825",66%,POOR,2.0,140,Medium HP,...,27,54.590045,100.4,66.9,174.0,2.626,14.5,11/15/2011,3,3
3,Ford,Ranger,220650,"$12,050","$7,850",65%,POOR,2.5,119,Medium HP,...,23,47.389531,117.5,69.4,200.7,3.086,20.0,1/14/2012,4,4
4,Ford,Escort,70227,"$12,070","$7,425",62%,POOR,2.0,110,Medium HP,...,30,44.083709,98.4,67.0,174.7,2.468,12.7,3/31/2012,5,5
5,Ford,Focus,175670,"$12,315","$8,670",70%,GOOD,2.0,107,Medium HP,...,30,43.117132,103.0,66.9,174.8,2.564,13.2,7/22/2012,6,6
6,Saturn,SC,24546,"$12,535","$10,590",84%,GOOD,1.9,100,Medium HP,...,33,40.700072,102.4,66.4,180.0,2.367,12.1,3/16/2011,7,7
7,Dodge,Neon,76034,"$12,640","$7,750",61%,POOR,2.0,132,Medium HP,...,29,52.084899,105.0,74.4,174.4,2.567,12.5,12/12/2011,8,8
8,Plymouth,Neon,32734,"$12,640","$7,750",61%,POOR,2.0,132,Medium HP,...,29,52.084899,105.0,74.4,174.4,2.559,12.5,4/26/2011,8,8
9,Honda,Civic,199685,"$12,885","$9,850",76%,GOOD,1.6,106,Medium HP,...,32,42.879097,103.2,67.1,175.1,2.339,11.9,10/21/2011,10,9
10,Toyota,Corolla,142535,"$13,108","$10,025",76%,GOOD,1.8,120,Medium HP,...,33,47.968972,97.0,66.7,174.0,2.420,13.2,4/11/2011,11,10
11,Chevrolet,Cavalier,145519,"$13,260","$9,250",70%,GOOD,2.2,115,Medium HP,...,27,46.363347,104.1,67.9,180.9,2.676,14.3,8/17/2011,12,11
12,Nissan,Sentra,42643,"$13,499","$8,450",63%,POOR,1.8,126,Medium HP,...,30,50.241978,99.8,67.3,177.5,2.593,13.2,8/31/2011,13,12
13,Chevrolet,Prizm,32299,"$13,960","$9,125",65%,POOR,1.8,120,Medium HP,...,33,48.297636,97.1,66.7,174.3,2.398,13.2,9/11/2011,14,13
14,Mitsubishi,Mirage,26232,"$13,987","$8,325",60%,POOR,1.8,113,Medium HP,...,30,45.832181,98.4,66.5,173.6,2.250,13.2,4/23/2012,15,14
15,Saturn,SW,5223,"$14,290","$10,790",76%,GOOD,1.9,124,Medium HP,...,31,49.865774,102.4,66.4,176.9,2.452,12.1,1/15/2011,16,15
16,Jeep,Wrangler,55557,"$14,460","$13,475",93%,GOOD,2.5,120,Medium HP,...,17,48.672898,93.4,66.7,152.0,3.045,19.0,3/4/2012,17,16
17,Volkswagen,Golf,9761,"$14,900","$11,425",77%,GOOD,2.0,115,Medium HP,...,26,46.943877,98.9,68.3,163.3,2.767,14.5,1/24/2011,18,17
18,Hyundai,Sonata,29450,"$14,999","$8,910",59%,POOR,2.4,148,Medium HP,...,25,58.758249,106.3,71.6,185.4,3.072,17.2,6/14/2012,19,18
19,Saturn,LS,49989,"$15,010","$9,900",66%,POOR,2.2,137,Medium HP,...,28,54.819728,106.5,69.0,190.4,2.910,13.1,12/4/2012,20,19
20,Honda,Accord,230902,"$15,350","$13,210",86%,GOOD,2.3,135,Medium HP,...,27,54.269548,106.9,70.3,188.8,2.932,17.1,5/20/2012,21,20
21,Volkswagen,Beetle,49463,"$15,900","$11,986",75%,GOOD,2.0,115,Medium HP,...,26,47.329632,98.9,67.9,161.1,2.769,14.5,10/20/2011,22,21
22,Plymouth,Breeze,5240,"$16,080","$9,800",61%,POOR,2.0,132,Medium HP,...,27,53.411898,108.0,71.0,186.3,2.942,16.0,11/14/2011,23,22
23,Mercury,Mystique,14351,"$16,240","$8,800",54%,POOR,2.0,125,Medium HP,...,28,50.997748,106.5,69.1,184.8,2.769,15.0,12/19/2012,24,23
24,Chrysler,Cirrus,32306,"$16,480","$12,640",77%,GOOD,2.0,132,Medium HP,...,27,53.566200,108.0,71.0,186.0,2.911,16.0,10/6/2011,25,24
25,Chevrolet,Malibu,135126,"$16,535","$11,225",68%,POOR,3.1,170,Medium HP,...,25,67.314462,107.0,69.4,190.4,3.051,15.0,3/19/2012,26,25
26,Mercury,Cougar,26529,"$16,540","$13,890",84%,GOOD,2.0,125,Medium HP,...,30,51.113474,106.4,69.6,185.0,2.892,16.0,2/23/2012,27,26
27,Volkswagen,Jetta,83721,"$16,700","$13,240",79%,GOOD,2.0,115,Medium HP,...,26,47.638237,98.9,68.3,172.3,2.853,14.5,8/27/2011,28,27
28,Toyota,Celica,33269,"$16,875","$15,445",92%,GOOD,1.8,140,Medium HP,...,31,56.496030,102.4,68.3,170.5,2.425,14.5,12/29/2012,29,28
29,Toyota,RAV4,25106,"$16,888","$13,325",79%,GOOD,2.0,127,Medium HP,...,27,51.955109,94.9,66.7,163.8,2.668,15.3,5/6/2011,30,29

In [46]:
df_dense = df.withColumn('denserank',dense_rank().over(Window.orderBy('Price'))).show()

+------------+--------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+---------+
|Manufacturer|   Model|Unit Sales|   Price|Year Resale Value|Retention %|Retention Value|Engine Size|Horsepower| HP Level|Vehicle_type|Fuel Efficiency|Power Perf Factor|Wheelbase|Width|Length|Curb Weight|Fuel Capacity|Latest Launch|denserank|
+------------+--------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+---------+
|      Saturn|      SL|     80620|$10,685 |          $9,200 |        86%|           GOOD|        1.9|       100|Medium HP|   Passenger|             33|      39.98642475|    102.4| 66.4| 176.9|      2.332|         12.1|    8/16/2012|        1|
|      Toyota|  Tacoma|     84087|$11,528 |          $9,575 |        83%|           GOOD|        2.4|       142|Medium HP|         Car|             23|      55.29711658|    103.3| 66.5| 178.7|       2.58|         15.1|     8/1/2011|        2|
|     Hyundai| Elantra|     66692|$11,799 |          $7,825 |        66%|           POOR|        2.0|       140|Medium HP|   Passenger|             27|      54.59004516|    100.4| 66.9| 174.0|      2.626|         14.5|   11/15/2011|        3|
|        Ford|  Ranger|    220650|$12,050 |          $7,850 |        65%|           POOR|        2.5|       119|Medium HP|         Car|             23|      47.38953131|    117.5| 69.4| 200.7|      3.086|         20.0|    1/14/2012|        4|
|        Ford|  Escort|     70227|$12,070 |          $7,425 |        62%|           POOR|        2.0|       110|Medium HP|   Passenger|             30|      44.08370946|     98.4| 67.0| 174.7|      2.468|         12.7|    3/31/2012|        5|
|        Ford|   Focus|    175670|$12,315 |          $8,670 |        70%|           GOOD|        2.0|       107|Medium HP|   Passenger|             30|      43.11713201|    103.0| 66.9| 174.8|      2.564|         13.2|    7/22/2012|        6|
|      Saturn|      SC|     24546|$12,535 |         $10,590 |        84%|           GOOD|        1.9|       100|Medium HP|   Passenger|             33|      40.70007242|    102.4| 66.4| 180.0|      2.367|         12.1|    3/16/2011|        7|
|       Dodge|    Neon|     76034|$12,640 |          $7,750 |        61%|           POOR|        2.0|       132|Medium HP|   Passenger|             29|      52.08489875|    105.0| 74.4| 174.4|      2.567|         12.5|   12/12/2011|        8|
|    Plymouth|    Neon|     32734|$12,640 |          $7,750 |        61%|           POOR|        2.0|       132|Medium HP|   Passenger|             29|      52.08489875|    105.0| 74.4| 174.4|      2.559|         12.5|    4/26/2011|        8|
|       Honda|   Civic|    199685|$12,885 |          $9,850 |        76%|           GOOD|        1.6|       106|Medium HP|   Passenger|             32|      42.87909734|    103.2| 67.1| 175.1|      2.339|         11.9|   10/21/2011|        9|
|      Toyota| Corolla|    142535|$13,108 |         $10,025 |        76%|           GOOD|        1.8|       120|Medium HP|   Passenger|             33|      47.96897242|     97.0| 66.7| 174.0|       2.42|         13.2|    4/11/2011|       10|
|   Chevrolet|Cavalier|    145519|$13,260 |          $9,250 |        70%|           GOOD|        2.2|       115|Medium HP|   Passenger|             27|      46.36334747|    104.1| 67.9| 180.9|      2.676|         14.3|    8/17/2011|       11|
|      Nissan|  Sentra|     42643|$13,499 |          $8,450 |        63%|           POOR|        1.8|       126|Medium HP|   Passenger|             30|      50.24197791|     99.8| 67.3| 177.5|      2.593|         13.2|    8/31/2011|       12|
|   Chevrolet|   Prizm|     32299|$13,960 |          $9,125 |        65%|           POOR|        1.8|       120|Medium HP|   Passenger|             33|       48.2976361|     97.1| 66.7| 174.3|      2.398|         13.2|    9/11/2011|       13|
|  Mitsubishi|  Mirage|     26232|$13,987 |          $8,325 |        60%|           POOR|        1.8|       113|Medium HP|   Passenger|             30|      45.83218056|     98.4| 66.5| 173.6|       2.25|         13.2|    4/23/2012|       14|
|      Saturn|      SW|      5223|$14,290 |         $10,790 |        76%|           GOOD|        1.9|       124|Medium HP|   Passenger|             31|      49.86577367|    102.4| 66.4| 176.9|      2.452|         12.1|    1/15/2011|       15|
|        Jeep|Wrangler|     55557|$14,460 |         $13,475 |        93%|           GOOD|        2.5|       120|Medium HP|         Car|             17|      48.67289791|     93.4| 66.7| 152.0|      3.045|         19.0|     3/4/2012|       16|
|  Volkswagen|    Golf|      9761|$14,900 |         $11,425 |        77%|           GOOD|        2.0|       115|Medium HP|   Passenger|             26|      46.94387676|     98.9| 68.3| 163.3|      2.767|         14.5|    1/24/2011|       17|
|     Hyundai|  Sonata|     29450|$14,999 |          $8,910 |        59%|           POOR|        2.4|       148|Medium HP|   Passenger|             25|        58.758249|    106.3| 71.6| 185.4|      3.072|         17.2|    6/14/2012|       18|
|      Saturn|      LS|     49989|$15,010 |          $9,900 |        66%|           POOR|        2.2|       137|Medium HP|   Passenger|             28|      54.81972825|    106.5| 69.0| 190.4|       2.91|         13.1|    12/4/2012|       19|
+------------+--------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+---------+
only showing top 20 rows