### PySpark

In [2]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("car_sales").getOrCreate()

df = spark.read.format('csv').option('inferSchema',True).option('header',True).load('C:/Users/shiva/Downloads/Car_sales.csv')

In [3]:
df.limit(3).toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch
0,Mercedes-B,CL500,954,"$85,500","$63,423",74%,GOOD,5.0,NaN,High HP,Passenger,20,141.100985,113.6,73.1,196.6,4.115,23.2,4/11/2011
1,Mercedes-B,SL-Class,3311,"$82,600","$58,600",71%,GOOD,5.0,NaN,High HP,Passenger,20,139.982294,99.0,71.3,177.1,4.125,21.1,3/17/2011
2,Porsche,Carrera Cabrio,1866,"$74,970","$67,550",90%,GOOD,3.4,300.0,High HP,Passenger,23,135.914710,92.6,69.5,174.5,3.075,17.0,7/11/2011

In [4]:
from pyspark.sql.types import *
from pyspark.sql.functions import *

In [ ]:
#df_select = df.select('Manufacturer','Model','Unit Sales','Price')
df_select = df.select(col('Manufacturer'),col('Model'),col('Unit Sales'),col('Price'))

df_select.limit(5).toPandas()

  Manufacturer           Model  Unit Sales     Price
0   Mercedes-B           CL500         954  $85,500
1   Mercedes-B        SL-Class        3311  $82,600
2      Porsche  Carrera Cabrio        1866  $74,970
3   Mercedes-B           CL500         954  $85,500
4   Mercedes-B        SL-Class        3311  $82,600

In [38]:
df.show()

+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|Manufacturer|         Model|Unit Sales|   Price|Year Resale Value|Retention %|Retention Value|Engine Size|Horsepower| HP Level|Vehicle_type|Fuel Efficiency|Power Perf Factor|Wheelbase|Width|Length|Curb Weight|Fuel Capacity|Latest Launch|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300|  High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300|  High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
|     Porsche| Carrera Coupe|      1280|$71,020 |         $60,625 |        85%|           GOOD|        3.4|       300|  High HP|   Passenger|             21|      134.3909754|     92.6| 69.5| 174.5|      3.032|         17.0|   12/21/2012|
|       Dodge|         Viper|       916|$69,725 |         $58,470 |        84%|           GOOD|        8.0|       450|  High HP|   Passenger|             16|       188.144323|     96.2| 75.7| 176.7|      3.375|         19.0|     8/7/2011|
|  Mercedes-B|       S-Class|     16774|$69,700 |         $50,375 |        72%|           GOOD|        4.3|       275|Medium HP|   Passenger|             21|      125.2738757|    121.5| 73.1| 203.1|      4.133|         23.2|    6/13/2011|
|        Audi|            A8|      1380|$62,000 |         $39,000 |        63%|           POOR|        4.2|       310|  High HP|   Passenger|             21|      134.6568582|    113.0| 74.0| 198.2|      3.902|         23.7|    2/27/2012|
|       Lexus|         LX470|      9126|$60,105 |         $43,870 |        73%|           GOOD|        4.7|       230|Medium HP|         Car|             15|       105.760458|    112.2| 76.4| 192.5|      5.401|         25.4|   10/30/2012|
|   Chevrolet|      Corvette|     17947|$55,705 |         $36,225 |        65%|           POOR|        5.7|       345|  High HP|   Passenger|             22|        141.14115|    104.5| 73.6| 179.7|       3.21|         19.1|    5/12/2012|
|       Lexus|         LS400|      6375|$54,005 |         $40,375 |        75%|           GOOD|        4.0|       290|Medium HP|   Passenger|             22|      124.4467163|    112.2| 72.0| 196.7|       3.89|         22.5|    3/29/2012|
|      Toyota|  Land Cruiser|      9835|$51,728 |         $34,080 |        66%|           POOR|        4.7|       230|Medium HP|         Car|             15|      102.5289842|    112.2| 76.4| 192.5|      5.115|         25.4|    9/25/2011|
|  Mercedes-B|       E-Class|     27602|$49,900 |         $41,450 |        83%|           GOOD|        3.2|       221|Medium HP|   Passenger|             25|       98.2497375|    111.5| 70.8| 189.4|      3.823|         21.1|    7/12/2011|
|       Lexus|         GS400|      3334|$46,305 |         $38,955 |        84%|           GOOD|        4.0|       300|  High HP|   Passenger|             21|      125.0133574|    110.2| 70.9| 189.2|      3.693|         19.8|   11/28/2012|
|    Cadillac|      Escalade|     14785|$46,225 |         $31,245 |        68%|           POOR|        5.7|       255|Medium HP|         Car|             15|      109.5091165|    117.5| 77.0| 201.2|      5.572|         30.0|    4/17/2012|
|       Volvo|           C70|      3493|$45,500 |         $34,175 |        75%|           GOOD|        2.3|       236|Medium HP|   Passenger|             23|      101.6233572|    104.9| 71.5| 185.7|      3.601|         18.5|    4/26/2011|
|    Cadillac|       Seville|     15943|$44,475 |         $27,100 |        61%|           POOR|        4.6|       275|Medium HP|   Passenger|             22|      115.6213578|    112.2| 75.0| 201.0|      3.875|         18.5|    4/29/2011|
|     Lincoln|      Town car|     48911|$43,330 |         $21,725 |        50%|           POOR|        4.6|       215|Medium HP|   Passenger|             21|       93.9579169|    117.7| 78.2| 215.3|      4.121|         19.0|     6/4/2012|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
only showing top 20 rows

Filter

In [39]:
#df.filter((col('Manufacturer')=='Audi')).show()
df_filter = df.filter((col('Manufacturer')=='Audi') & (col('Retention Value') == 'GOOD'))

df_filter.toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch
0,Audi,A6,18780,"$33,950","$23,555",69%,GOOD,2.8,200,Medium HP,Passenger,22,84.565105,108.7,76.1,192.0,3.561,18.5,8/9/2011
1,Audi,A4,20397,"$23,990","$22,255",93%,GOOD,1.8,150,Medium HP,Passenger,27,62.777639,102.6,68.2,178.0,2.998,16.4,10/8/2011

In [40]:
df.show()

+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|Manufacturer|         Model|Unit Sales|   Price|Year Resale Value|Retention %|Retention Value|Engine Size|Horsepower| HP Level|Vehicle_type|Fuel Efficiency|Power Perf Factor|Wheelbase|Width|Length|Curb Weight|Fuel Capacity|Latest Launch|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300|  High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300|  High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
|     Porsche| Carrera Coupe|      1280|$71,020 |         $60,625 |        85%|           GOOD|        3.4|       300|  High HP|   Passenger|             21|      134.3909754|     92.6| 69.5| 174.5|      3.032|         17.0|   12/21/2012|
|       Dodge|         Viper|       916|$69,725 |         $58,470 |        84%|           GOOD|        8.0|       450|  High HP|   Passenger|             16|       188.144323|     96.2| 75.7| 176.7|      3.375|         19.0|     8/7/2011|
|  Mercedes-B|       S-Class|     16774|$69,700 |         $50,375 |        72%|           GOOD|        4.3|       275|Medium HP|   Passenger|             21|      125.2738757|    121.5| 73.1| 203.1|      4.133|         23.2|    6/13/2011|
|        Audi|            A8|      1380|$62,000 |         $39,000 |        63%|           POOR|        4.2|       310|  High HP|   Passenger|             21|      134.6568582|    113.0| 74.0| 198.2|      3.902|         23.7|    2/27/2012|
|       Lexus|         LX470|      9126|$60,105 |         $43,870 |        73%|           GOOD|        4.7|       230|Medium HP|         Car|             15|       105.760458|    112.2| 76.4| 192.5|      5.401|         25.4|   10/30/2012|
|   Chevrolet|      Corvette|     17947|$55,705 |         $36,225 |        65%|           POOR|        5.7|       345|  High HP|   Passenger|             22|        141.14115|    104.5| 73.6| 179.7|       3.21|         19.1|    5/12/2012|
|       Lexus|         LS400|      6375|$54,005 |         $40,375 |        75%|           GOOD|        4.0|       290|Medium HP|   Passenger|             22|      124.4467163|    112.2| 72.0| 196.7|       3.89|         22.5|    3/29/2012|
|      Toyota|  Land Cruiser|      9835|$51,728 |         $34,080 |        66%|           POOR|        4.7|       230|Medium HP|         Car|             15|      102.5289842|    112.2| 76.4| 192.5|      5.115|         25.4|    9/25/2011|
|  Mercedes-B|       E-Class|     27602|$49,900 |         $41,450 |        83%|           GOOD|        3.2|       221|Medium HP|   Passenger|             25|       98.2497375|    111.5| 70.8| 189.4|      3.823|         21.1|    7/12/2011|
|       Lexus|         GS400|      3334|$46,305 |         $38,955 |        84%|           GOOD|        4.0|       300|  High HP|   Passenger|             21|      125.0133574|    110.2| 70.9| 189.2|      3.693|         19.8|   11/28/2012|
|    Cadillac|      Escalade|     14785|$46,225 |         $31,245 |        68%|           POOR|        5.7|       255|Medium HP|         Car|             15|      109.5091165|    117.5| 77.0| 201.2|      5.572|         30.0|    4/17/2012|
|       Volvo|           C70|      3493|$45,500 |         $34,175 |        75%|           GOOD|        2.3|       236|Medium HP|   Passenger|             23|      101.6233572|    104.9| 71.5| 185.7|      3.601|         18.5|    4/26/2011|
|    Cadillac|       Seville|     15943|$44,475 |         $27,100 |        61%|           POOR|        4.6|       275|Medium HP|   Passenger|             22|      115.6213578|    112.2| 75.0| 201.0|      3.875|         18.5|    4/29/2011|
|     Lincoln|      Town car|     48911|$43,330 |         $21,725 |        50%|           POOR|        4.6|       215|Medium HP|   Passenger|             21|       93.9579169|    117.7| 78.2| 215.3|      4.121|         19.0|     6/4/2012|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
only showing top 20 rows

In [41]:
df_multi_filter = df.filter(
    (col('Horsepower').isNull()) & 
    (col('Retention Value').isin('GOOD', 'POOR'))
    )

df_multi_filter.toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch
0,BMW,528i,17527,"$38,900","$36,125",93%,GOOD,2.8,NaN,Medium HP,Passenger,25,83.998724,111.4,70.9,188.0,3.472,18.5,4/4/2011
1,Acura,Integra,16919,"$21,500","$16,360",76%,GOOD,1.8,NaN,Medium HP,Passenger,28,58.280150,101.2,67.3,172.4,2.639,13.2,2/2/2012
2,Dodge,Ram Van,31038,"$18,575","$13,425",72%,GOOD,3.9,NaN,Medium HP,Car,16,70.078322,127.2,78.8,208.5,4.298,32.0,7/26/2012
3,Dodge,Dakota,111313,"$16,980","$11,260",66%,POOR,2.5,NaN,Medium HP,Car,19,49.645002,131.0,71.5,215.0,3.557,22.0,11/25/2011

In [42]:
df.withColumnRenamed('Unit Sales','Unit_Sales').show(3)

+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+--------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|Manufacturer|         Model|Unit_Sales|   Price|Year Resale Value|Retention %|Retention Value|Engine Size|Horsepower|HP Level|Vehicle_type|Fuel Efficiency|Power Perf Factor|Wheelbase|Width|Length|Curb Weight|Fuel Capacity|Latest Launch|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+--------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|       302| High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|       302| High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300| High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+--------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
only showing top 3 rows

In [43]:
for c in ['Price', 'Year Resale Value']:
    df = df.withColumn(c, regexp_replace(col(c), '[^0-9.-]', '').cast('double'))

df.printSchema()

root
 |-- Manufacturer: string (nullable = true)
 |-- Model: string (nullable = true)
 |-- Unit Sales: integer (nullable = true)
 |-- Price: double (nullable = true)
 |-- Year Resale Value: double (nullable = true)
 |-- Retention %: string (nullable = true)
 |-- Retention Value: string (nullable = true)
 |-- Engine Size: double (nullable = true)
 |-- Horsepower: integer (nullable = true)
 |-- HP Level: string (nullable = true)
 |-- Vehicle_type: string (nullable = true)
 |-- Fuel Efficiency: integer (nullable = true)
 |-- Power Perf Factor: double (nullable = true)
 |-- Wheelbase: double (nullable = true)
 |-- Width: double (nullable = true)
 |-- Length: double (nullable = true)
 |-- Curb Weight: double (nullable = true)
 |-- Fuel Capacity: double (nullable = true)
 |-- Latest Launch: string (nullable = true)

In [44]:
df2 = df.withColumn('Price_Diff', 
                    col('Price') - col('Year Resale Value'))

df2.limit(3).toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch,Price_Diff
0,Mercedes-B,CL500,954,85500.0,63423.0,74%,GOOD,5.0,302,High HP,Passenger,20,141.100985,113.6,73.1,196.6,4.115,23.2,4/11/2011,22077.0
1,Mercedes-B,SL-Class,3311,82600.0,58600.0,71%,GOOD,5.0,302,High HP,Passenger,20,139.982294,99.0,71.3,177.1,4.125,21.1,3/17/2011,24000.0
2,Porsche,Carrera Cabrio,1866,74970.0,67550.0,90%,GOOD,3.4,300,High HP,Passenger,23,135.914710,92.6,69.5,174.5,3.075,17.0,7/11/2011,7420.0

In [7]:
df_reg = df.withColumn('HP Level',regexp_replace(col('HP Level'),"Medium HP","MHP"))\
            .withColumn('HP Level',regexp_replace(col('HP Level'),"High HP","HHP"))

df_reg.limit(20).toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch
0,Acura,Integra,16919,"$21,500","$16,360",76%,GOOD,1.8,NaN,MHP,Passenger,28,58.280150,101.2,67.3,172.4,2.639,13.2,2/2/2012
1,Acura,TL,39384,"$28,400","$19,875",70%,GOOD,3.2,225.0,MHP,Passenger,25,91.370778,108.1,70.3,192.9,3.517,17.2,6/3/2011
2,Acura,RL,8588,"$42,000","$29,725",71%,GOOD,3.5,210.0,MHP,Passenger,22,91.389779,114.6,71.4,196.6,3.850,18.0,3/10/2011
3,Audi,A4,20397,"$23,990","$22,255",93%,GOOD,1.8,150.0,MHP,Passenger,27,62.777639,102.6,68.2,178.0,2.998,16.4,10/8/2011
4,Audi,A6,18780,"$33,950","$23,555",69%,GOOD,2.8,200.0,MHP,Passenger,22,84.565105,108.7,76.1,192.0,3.561,18.5,8/9/2011
5,Audi,A8,1380,"$62,000","$39,000",63%,POOR,4.2,310.0,HHP,Passenger,21,134.656858,113.0,74.0,198.2,3.902,23.7,2/27/2012
6,BMW,323i,19747,"$26,990","$24,500",91%,GOOD,2.5,170.0,MHP,Passenger,26,71.191207,107.3,68.4,176.0,3.179,16.6,6/28/2011
7,BMW,328i,9231,"$33,400","$28,675",86%,GOOD,2.8,193.0,MHP,Passenger,24,81.877069,107.3,68.5,176.0,3.197,16.6,1/29/2012
8,BMW,528i,17527,"$38,900","$36,125",93%,GOOD,2.8,NaN,MHP,Passenger,25,83.998724,111.4,70.9,188.0,3.472,18.5,4/4/2011
9,Buick,Century,91561,"$21,975","$12,475",57%,POOR,3.1,175.0,MHP,Passenger,25,71.181451,109.0,72.7,194.6,3.368,17.5,11/2/2011
10,Buick,Regal,39350,"$25,300","$13,740",54%,POOR,3.8,240.0,MHP,Passenger,23,95.636703,109.0,72.7,196.2,3.543,17.5,9/3/2011
11,Buick,Park Avenue,27851,"$31,965","$20,190",63%,POOR,3.8,205.0,MHP,Passenger,24,85.828408,113.8,74.7,206.8,3.778,18.5,3/23/2012
12,Buick,LeSabre,83257,"$27,885","$13,360",48%,POOR,3.8,205.0,MHP,Passenger,25,84.254526,112.2,73.5,200.0,3.591,17.5,7/23/2011
13,Cadillac,DeVille,63729,"$39,895","$22,525",56%,POOR,4.6,275.0,MHP,Passenger,22,113.854598,115.3,74.5,207.2,3.978,18.5,2/23/2012
14,Cadillac,Seville,15943,"$44,475","$27,100",61%,POOR,4.6,275.0,MHP,Passenger,22,115.621358,112.2,75.0,201.0,3.875,18.5,4/29/2011
15,Cadillac,Eldorado,6536,"$39,665","$25,725",65%,POOR,4.6,275.0,MHP,Passenger,22,113.765874,108.0,75.5,200.6,3.843,19.0,11/27/2011
16,Cadillac,Catera,11185,"$31,010","$18,225",59%,POOR,3.0,200.0,MHP,Passenger,22,83.483094,107.4,70.3,194.8,3.770,18.0,9/28/2011
17,Cadillac,Escalade,14785,"$46,225","$31,245",68%,POOR,5.7,255.0,MHP,Car,15,109.509117,117.5,77.0,201.2,5.572,30.0,4/17/2012
18,Chevrolet,Cavalier,145519,"$13,260","$9,250",70%,GOOD,2.2,115.0,MHP,Passenger,27,46.363347,104.1,67.9,180.9,2.676,14.3,8/17/2011
19,Chevrolet,Malibu,135126,"$16,535","$11,225",68%,POOR,3.1,170.0,MHP,Passenger,25,67.314462,107.0,69.4,190.4,3.051,15.0,3/19/2012

In [8]:
df.printSchema()

root
 |-- Manufacturer: string (nullable = true)
 |-- Model: string (nullable = true)
 |-- Unit Sales: integer (nullable = true)
 |-- Price: string (nullable = true)
 |-- Year Resale Value: string (nullable = true)
 |-- Retention %: string (nullable = true)
 |-- Retention Value: string (nullable = true)
 |-- Engine Size: double (nullable = true)
 |-- Horsepower: integer (nullable = true)
 |-- HP Level: string (nullable = true)
 |-- Vehicle_type: string (nullable = true)
 |-- Fuel Efficiency: integer (nullable = true)
 |-- Power Perf Factor: double (nullable = true)
 |-- Wheelbase: double (nullable = true)
 |-- Width: double (nullable = true)
 |-- Length: double (nullable = true)
 |-- Curb Weight: double (nullable = true)
 |-- Fuel Capacity: double (nullable = true)
 |-- Latest Launch: string (nullable = true)

### Sort

In [14]:
#df_sort = df.sort(col('Price').desc())

df_sort = df.sort(['Engine Size','Horsepower'], ascending = [0,0])
df_sort.limit(20).toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch
0,Dodge,Viper,916,"$69,725","$58,470",84%,GOOD,8.0,450,High HP,Passenger,16,188.144323,96.2,75.7,176.7,3.375,19.0,8/7/2011
1,Chevrolet,Corvette,17947,"$55,705","$36,225",65%,POOR,5.7,345,High HP,Passenger,22,141.141150,104.5,73.6,179.7,3.210,19.1,5/12/2012
2,Cadillac,Escalade,14785,"$46,225","$31,245",68%,POOR,5.7,255,Medium HP,Car,15,109.509117,117.5,77.0,201.2,5.572,30.0,4/17/2012
3,Lincoln,Navigator,22925,"$42,660","$20,765",49%,POOR,5.4,300,High HP,Car,15,123.972047,119.0,79.9,204.8,5.393,30.0,12/23/2012
4,Dodge,Durango,101323,"$26,310","$21,436",81%,GOOD,5.2,230,Medium HP,Car,17,92.854125,115.7,71.7,193.5,4.394,25.0,6/27/2012
5,Dodge,Ram Pickup,227061,"$19,460","$15,060",77%,GOOD,5.2,230,Medium HP,Car,17,90.211700,138.7,79.3,224.2,4.470,26.0,3/6/2012
6,Mercedes-B,SL-Class,3311,"$82,600","$58,600",71%,GOOD,5.0,302,High HP,Passenger,20,139.982294,99.0,71.3,177.1,4.125,21.1,3/17/2011
7,Mercedes-B,CL500,954,"$85,500","$63,423",74%,GOOD,5.0,302,High HP,Passenger,20,141.100985,113.6,73.1,196.6,4.115,23.2,4/11/2011
8,Lexus,LX470,9126,"$60,105","$43,870",73%,GOOD,4.7,230,Medium HP,Car,15,105.760458,112.2,76.4,192.5,5.401,25.4,10/30/2012
9,Toyota,Land Cruiser,9835,"$51,728","$34,080",66%,POOR,4.7,230,Medium HP,Car,15,102.528984,112.2,76.4,192.5,5.115,25.4,9/25/2011
10,Cadillac,DeVille,63729,"$39,895","$22,525",56%,POOR,4.6,275,Medium HP,Passenger,22,113.854598,115.3,74.5,207.2,3.978,18.5,2/23/2012
11,Cadillac,Seville,15943,"$44,475","$27,100",61%,POOR,4.6,275,Medium HP,Passenger,22,115.621358,112.2,75.0,201.0,3.875,18.5,4/29/2011
12,Cadillac,Eldorado,6536,"$39,665","$25,725",65%,POOR,4.6,275,Medium HP,Passenger,22,113.765874,108.0,75.5,200.6,3.843,19.0,11/27/2011
13,Lincoln,Continental,13798,"$39,080","$20,525",53%,POOR,4.6,275,Medium HP,Passenger,22,113.540207,109.0,73.6,208.5,3.868,20.0,8/3/2012
14,Ford,Expedition,125338,"$36,135","$23,575",65%,POOR,4.6,240,Medium HP,Car,16,100.024802,119.0,78.7,204.6,4.808,26.0,9/14/2012
15,Ford,F-Series,540561,"$26,935","$15,075",56%,POOR,4.6,220,Medium HP,Car,18,89.401935,138.5,79.1,224.5,4.241,25.1,8/16/2012
16,Lincoln,Town car,48911,"$43,330","$21,725",50%,POOR,4.6,215,Medium HP,Passenger,21,93.957917,117.7,78.2,215.3,4.121,19.0,6/4/2012
17,Ford,Crown Victoria,63403,"$22,195","$14,210",64%,POOR,4.6,200,Medium HP,Passenger,21,80.499537,114.7,78.2,212.0,3.908,19.0,9/26/2011
18,Mercury,Grand Marquis,81174,"$22,605","$14,875",66%,POOR,4.6,200,Medium HP,Passenger,21,80.657696,114.7,78.2,212.0,3.958,19.0,7/24/2012
19,Mercedes-B,S-Class,16774,"$69,700","$50,375",72%,GOOD,4.3,275,Medium HP,Passenger,21,125.273876,121.5,73.1,203.1,4.133,23.2,6/13/2011

In [20]:
df_dup = df.dropDuplicates()
df_dup.limit(20).toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch
0,Chrysler,LHS,13462,"$28,340","$17,325",61%,POOR,3.5,253,Medium HP,Passenger,23,101.329281,113.0,74.4,207.7,3.564,17.0,5/8/2012
1,Lexus,GS400,3334,"$46,305","$38,955",84%,GOOD,4.0,300,High HP,Passenger,21,125.013357,110.2,70.9,189.2,3.693,19.8,11/28/2012
2,Cadillac,Catera,11185,"$31,010","$18,225",59%,POOR,3.0,200,Medium HP,Passenger,22,83.483094,107.4,70.3,194.8,3.770,18.0,9/28/2011
3,Buick,Regal,39350,"$25,300","$13,740",54%,POOR,3.8,240,Medium HP,Passenger,23,95.636703,109.0,72.7,196.2,3.543,17.5,9/3/2011
4,Jeep,Wrangler,55557,"$14,460","$13,475",93%,GOOD,2.5,120,Medium HP,Car,17,48.672898,93.4,66.7,152.0,3.045,19.0,3/4/2012
5,Ford,Windstar,155787,"$21,410","$13,175",62%,POOR,3.0,150,Medium HP,Car,21,62.095048,120.7,76.6,200.9,3.761,26.0,2/25/2012
6,Honda,CR-V,73203,"$20,550","$17,710",86%,GOOD,2.0,146,Medium HP,Car,24,60.087967,103.2,68.9,177.6,3.219,15.3,3/21/2012
7,Dodge,Avenger,4734,"$19,045","$12,545",66%,POOR,2.5,163,Medium HP,Passenger,24,65.650508,103.7,69.1,190.2,2.879,15.9,7/1/2012
8,Pontiac,Bonneville,35945,"$23,755","$13,225",56%,POOR,3.8,205,Medium HP,Passenger,24,82.661356,112.2,72.6,202.5,3.590,17.5,5/18/2011
9,Hyundai,Sonata,29450,"$14,999","$8,910",59%,POOR,2.4,148,Medium HP,Passenger,25,58.758249,106.3,71.6,185.4,3.072,17.2,6/14/2012
10,Cadillac,Seville,15943,"$44,475","$27,100",61%,POOR,4.6,275,Medium HP,Passenger,22,115.621358,112.2,75.0,201.0,3.875,18.5,4/29/2011
11,Chrysler,Concorde,31148,"$22,245","$13,725",62%,POOR,2.7,200,Medium HP,Passenger,26,80.023782,113.0,74.4,209.1,3.452,17.0,6/6/2012
12,Volvo,V70,17531,"$28,800","$20,223",70%,GOOD,2.4,168,Medium HP,Passenger,25,71.155978,104.9,69.3,186.2,3.259,17.9,6/25/2011
13,Dodge,Caravan,181749,"$19,565","$12,025",61%,POOR,2.4,150,Medium HP,Car,24,61.227000,113.3,76.8,186.3,3.533,20.0,9/1/2011
14,Dodge,Intrepid,88028,"$22,505","$12,275",55%,POOR,2.7,202,Medium HP,Passenger,22,80.831470,113.0,74.7,203.7,3.489,17.0,6/2/2012
15,Mercury,Mountaineer,27609,"$27,560","$20,430",74%,GOOD,4.0,210,Medium HP,Car,18,85.949744,111.6,70.2,190.1,3.876,21.0,2/13/2008
16,Lexus,ES300,24072,"$31,505","$26,975",86%,GOOD,3.0,210,Medium HP,Passenger,23,87.211001,105.1,70.5,190.2,3.373,18.5,7/9/2012
17,Volkswagen,Jetta,83721,"$16,700","$13,240",79%,GOOD,2.0,115,Medium HP,Passenger,26,47.638237,98.9,68.3,172.3,2.853,14.5,8/27/2011
18,Pontiac,Sunfire,51645,"$21,610","$13,790",64%,POOR,2.4,150,Medium HP,Passenger,27,62.015870,104.1,68.4,181.9,2.906,15.0,1/25/2012
19,Volkswagen,GTI,5596,"$17,500","$13,760",79%,GOOD,2.0,115,Medium HP,Passenger,26,47.946841,98.9,68.3,163.3,2.762,14.6,4/1/2011

In [41]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("data1").getOrCreate()
spark = SparkSession.builder.appName("data2").getOrCreate()

data1 = [
    ('Shiva',1),
    ('Jashvitha',2)
]

schema1 = 'name STRING, id STRING'

df_data1 = spark.createDataFrame(data1,schema1)

data2 = [
    (3,'Dhiyanshi'),
    (4,'Badugu')
]
schema2 = 'id STRING, name STRING'

df_data2 = spark.createDataFrame(data2,schema2)

In [42]:
df_data1.toPandas()
#df_data2.toPandas()

        name id
0      Shiva  1
1  Jashvitha  2

In [44]:
#df_data1.union(df_data2).toPandas()
df_data1.unionByName(df_data2).toPandas()

        name id
0      Shiva  1
1  Jashvitha  2
2  Dhiyanshi  3
3     Badugu  4

In [6]:
df.limit(5).toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch
0,Mercedes-B,CL500,954,"$85,500","$63,423",74%,GOOD,5.0,302,High HP,Passenger,20,141.100985,113.6,73.1,196.6,4.115,23.2,4/11/2011
1,Mercedes-B,SL-Class,3311,"$82,600","$58,600",71%,GOOD,5.0,302,High HP,Passenger,20,139.982294,99.0,71.3,177.1,4.125,21.1,3/17/2011
2,Porsche,Carrera Cabrio,1866,"$74,970","$67,550",90%,GOOD,3.4,300,High HP,Passenger,23,135.914710,92.6,69.5,174.5,3.075,17.0,7/11/2011
3,Mercedes-B,CL500,954,"$85,500","$63,423",74%,GOOD,5.0,302,High HP,Passenger,20,141.100985,113.6,73.1,196.6,4.115,23.2,4/11/2011
4,Mercedes-B,SL-Class,3311,"$82,600","$58,600",71%,GOOD,5.0,302,High HP,Passenger,20,139.982294,99.0,71.3,177.1,4.125,21.1,3/17/2011

In [9]:
df_upper = df.select(upper('Manufacturer').alias('UpperCase_Manufacturer'))

df_upper.limit(10).toPandas()

  UpperCase_Manufacturer
0             MERCEDES-B
1             MERCEDES-B
2                PORSCHE
3             MERCEDES-B
4             MERCEDES-B
5                PORSCHE
6                PORSCHE
7                  DODGE
8             MERCEDES-B
9                   AUDI

### DateFormat

In [19]:
#df = df.withColumn('curr_date',current_date())

#df = df.withColumn('7DaysAfter',date_add('curr_date',7))
df = df.withColumn('7DaysBefore',date_add('curr_date',-7))
df.limit(3).toPandas()

  Manufacturer           Model   curr_date  7DaysAfter  diffdate 7DaysBefore
0   Mercedes-B           CL500  2026-10-11  2026-10-18         7  2026-10-04
1   Mercedes-B        SL-Class  2026-10-11  2026-10-18         7  2026-10-04
2      Porsche  Carrera Cabrio  2026-10-11  2026-10-18         7  2026-10-04

In [33]:
df_dates = df.withColumn('curr_date', current_date()) \
             .withColumn('7DaysAfter', date_add('curr_date', 7)) \
             .withColumn('diffdate', datediff('7DaysAfter', 'curr_date')) \
             .withColumn('curr_date', date_format('curr_date', 'dd-MM-yyyy')) \
             .withColumn('7DaysAfter', date_format('7DaysAfter', 'dd-MM-yyyy')) \
             .select('Manufacturer', 'Model', 'curr_date', '7DaysAfter', 'diffdate')

df_dates.limit(3).toPandas()

  Manufacturer           Model   curr_date  7DaysAfter  diffdate
0   Mercedes-B           CL500  11-10-2026  18-10-2026         7
1   Mercedes-B        SL-Class  11-10-2026  18-10-2026         7
2      Porsche  Carrera Cabrio  11-10-2026  18-10-2026         7

### Handling Nulls values
## Dropping Nulls

In [45]:
df_null = df.dropna('any')

df_null.limit(5).toPandas()

,Manufacturer,Model,Unit Sales,Price,Year Resale Value,Retention %,Retention Value,Engine Size,Horsepower,HP Level,Vehicle_type,Fuel Efficiency,Power Perf Factor,Wheelbase,Width,Length,Curb Weight,Fuel Capacity,Latest Launch
0,Porsche,Carrera Cabrio,1866,"$74,970","$67,550",90%,GOOD,3.4,300,High HP,Passenger,23,135.914710,92.6,69.5,174.5,3.075,17.0,7/11/2011
1,Mercedes-B,CL500,954,"$85,500","$63,423",74%,GOOD,5.0,302,High HP,Passenger,20,141.100985,113.6,73.1,196.6,4.115,23.2,4/11/2011
2,Mercedes-B,SL-Class,3311,"$82,600","$58,600",71%,GOOD,5.0,302,High HP,Passenger,20,139.982294,99.0,71.3,177.1,4.125,21.1,3/17/2011
3,Porsche,Carrera Cabrio,1866,"$74,970","$67,550",90%,GOOD,3.4,300,High HP,Passenger,23,135.914710,92.6,69.5,174.5,3.075,17.0,7/11/2011
4,Porsche,Carrera Coupe,1280,"$71,020","$60,625",85%,GOOD,3.4,300,High HP,Passenger,21,134.390975,92.6,69.5,174.5,3.032,17.0,12/21/2012

In [46]:
df.dropna('any')                              # drop rows with a null in ANY column (the default)
df.dropna(subset=['Horsepower'])              # drop rows only if Horsepower is null
df.dropna(thresh=15)                          # keep rows with at least 15 non-null values

DataFrame[Manufacturer: string, Model: string, Unit Sales: int, Price: string, Year Resale Value: string, Retention %: string, Retention Value: string, Engine Size: double, Horsepower: int, HP Level: string, Vehicle_type: string, Fuel Efficiency: int, Power Perf Factor: double, Wheelbase: double, Width: double, Length: double, Curb Weight: double, Fuel Capacity: double, Latest Launch: string]

In [48]:
df.show()
print(df.count(), df_null.count())

+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|Manufacturer|         Model|Unit Sales|   Price|Year Resale Value|Retention %|Retention Value|Engine Size|Horsepower| HP Level|Vehicle_type|Fuel Efficiency|Power Perf Factor|Wheelbase|Width|Length|Curb Weight|Fuel Capacity|Latest Launch|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|      NULL|  High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|      NULL|  High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300|  High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300|  High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
|     Porsche| Carrera Coupe|      1280|$71,020 |         $60,625 |        85%|           GOOD|        3.4|       300|  High HP|   Passenger|             21|      134.3909754|     92.6| 69.5| 174.5|      3.032|         17.0|   12/21/2012|
|       Dodge|         Viper|       916|$69,725 |         $58,470 |        84%|           GOOD|        8.0|       450|  High HP|   Passenger|             16|       188.144323|     96.2| 75.7| 176.7|      3.375|         19.0|     8/7/2011|
|  Mercedes-B|       S-Class|     16774|$69,700 |         $50,375 |        72%|           GOOD|        4.3|       275|Medium HP|   Passenger|             21|      125.2738757|    121.5| 73.1| 203.1|      4.133|         23.2|    6/13/2011|
|        Audi|            A8|      1380|$62,000 |         $39,000 |        63%|           POOR|        4.2|       310|  High HP|   Passenger|             21|      134.6568582|    113.0| 74.0| 198.2|      3.902|         23.7|    2/27/2012|
|       Lexus|         LX470|      9126|$60,105 |         $43,870 |        73%|           GOOD|        4.7|       230|Medium HP|         Car|             15|       105.760458|    112.2| 76.4| 192.5|      5.401|         25.4|   10/30/2012|
|   Chevrolet|      Corvette|     17947|$55,705 |         $36,225 |        65%|           POOR|        5.7|       345|  High HP|   Passenger|             22|        141.14115|    104.5| 73.6| 179.7|       3.21|         19.1|    5/12/2012|
|       Lexus|         LS400|      6375|$54,005 |         $40,375 |        75%|           GOOD|        4.0|       290|Medium HP|   Passenger|             22|      124.4467163|    112.2| 72.0| 196.7|       3.89|         22.5|    3/29/2012|
|      Toyota|  Land Cruiser|      9835|$51,728 |         $34,080 |        66%|           POOR|        4.7|       230|Medium HP|         Car|             15|      102.5289842|    112.2| 76.4| 192.5|      5.115|         25.4|    9/25/2011|
|  Mercedes-B|       E-Class|     27602|$49,900 |         $41,450 |        83%|           GOOD|        3.2|       221|Medium HP|   Passenger|             25|       98.2497375|    111.5| 70.8| 189.4|      3.823|         21.1|    7/12/2011|
|       Lexus|         GS400|      3334|$46,305 |         $38,955 |        84%|           GOOD|        4.0|       300|  High HP|   Passenger|             21|      125.0133574|    110.2| 70.9| 189.2|      3.693|         19.8|   11/28/2012|
|    Cadillac|      Escalade|     14785|$46,225 |         $31,245 |        68%|           POOR|        5.7|       255|Medium HP|         Car|             15|      109.5091165|    117.5| 77.0| 201.2|      5.572|         30.0|    4/17/2012|
|       Volvo|           C70|      3493|$45,500 |         $34,175 |        75%|           GOOD|        2.3|       236|Medium HP|   Passenger|             23|      101.6233572|    104.9| 71.5| 185.7|      3.601|         18.5|    4/26/2011|
|    Cadillac|       Seville|     15943|$44,475 |         $27,100 |        61%|           POOR|        4.6|       275|Medium HP|   Passenger|             22|      115.6213578|    112.2| 75.0| 201.0|      3.875|         18.5|    4/29/2011|
|     Lincoln|      Town car|     48911|$43,330 |         $21,725 |        50%|           POOR|        4.6|       215|Medium HP|   Passenger|             21|       93.9579169|    117.7| 78.2| 215.3|      4.121|         19.0|     6/4/2012|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
only showing top 20 rows
158 152

### Replace nullvalues

In [66]:
df.fillna(0, subset=['Horsepower'])\
    .filter(col('Horsepower') == 0)\
    .select('Manufacturer', 'Model', 'Horsepower') \
    .show()

+------------+--------+----------+
|Manufacturer|   Model|Horsepower|
+------------+--------+----------+
|  Mercedes-B|   CL500|         0|
|  Mercedes-B|SL-Class|         0|
|         BMW|    528i|         0|
|       Acura| Integra|         0|
|       Dodge| Ram Van|         0|
|       Dodge|  Dakota|         0|
+------------+--------+----------+

In [67]:
df.show()

+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|Manufacturer|         Model|Unit Sales|   Price|Year Resale Value|Retention %|Retention Value|Engine Size|Horsepower| HP Level|Vehicle_type|Fuel Efficiency|Power Perf Factor|Wheelbase|Width|Length|Curb Weight|Fuel Capacity|Latest Launch|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|      NULL|  High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|      NULL|  High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300|  High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
|  Mercedes-B|         CL500|       954|$85,500 |         $63,423 |        74%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      141.1009845|    113.6| 73.1| 196.6|      4.115|         23.2|    4/11/2011|
|  Mercedes-B|      SL-Class|      3311|$82,600 |         $58,600 |        71%|           GOOD|        5.0|       302|  High HP|   Passenger|             20|      139.9822936|     99.0| 71.3| 177.1|      4.125|         21.1|    3/17/2011|
|     Porsche|Carrera Cabrio|      1866|$74,970 |         $67,550 |        90%|           GOOD|        3.4|       300|  High HP|   Passenger|             23|      135.9147096|     92.6| 69.5| 174.5|      3.075|         17.0|    7/11/2011|
|     Porsche| Carrera Coupe|      1280|$71,020 |         $60,625 |        85%|           GOOD|        3.4|       300|  High HP|   Passenger|             21|      134.3909754|     92.6| 69.5| 174.5|      3.032|         17.0|   12/21/2012|
|       Dodge|         Viper|       916|$69,725 |         $58,470 |        84%|           GOOD|        8.0|       450|  High HP|   Passenger|             16|       188.144323|     96.2| 75.7| 176.7|      3.375|         19.0|     8/7/2011|
|  Mercedes-B|       S-Class|     16774|$69,700 |         $50,375 |        72%|           GOOD|        4.3|       275|Medium HP|   Passenger|             21|      125.2738757|    121.5| 73.1| 203.1|      4.133|         23.2|    6/13/2011|
|        Audi|            A8|      1380|$62,000 |         $39,000 |        63%|           POOR|        4.2|       310|  High HP|   Passenger|             21|      134.6568582|    113.0| 74.0| 198.2|      3.902|         23.7|    2/27/2012|
|       Lexus|         LX470|      9126|$60,105 |         $43,870 |        73%|           GOOD|        4.7|       230|Medium HP|         Car|             15|       105.760458|    112.2| 76.4| 192.5|      5.401|         25.4|   10/30/2012|
|   Chevrolet|      Corvette|     17947|$55,705 |         $36,225 |        65%|           POOR|        5.7|       345|  High HP|   Passenger|             22|        141.14115|    104.5| 73.6| 179.7|       3.21|         19.1|    5/12/2012|
|       Lexus|         LS400|      6375|$54,005 |         $40,375 |        75%|           GOOD|        4.0|       290|Medium HP|   Passenger|             22|      124.4467163|    112.2| 72.0| 196.7|       3.89|         22.5|    3/29/2012|
|      Toyota|  Land Cruiser|      9835|$51,728 |         $34,080 |        66%|           POOR|        4.7|       230|Medium HP|         Car|             15|      102.5289842|    112.2| 76.4| 192.5|      5.115|         25.4|    9/25/2011|
|  Mercedes-B|       E-Class|     27602|$49,900 |         $41,450 |        83%|           GOOD|        3.2|       221|Medium HP|   Passenger|             25|       98.2497375|    111.5| 70.8| 189.4|      3.823|         21.1|    7/12/2011|
|       Lexus|         GS400|      3334|$46,305 |         $38,955 |        84%|           GOOD|        4.0|       300|  High HP|   Passenger|             21|      125.0133574|    110.2| 70.9| 189.2|      3.693|         19.8|   11/28/2012|
|    Cadillac|      Escalade|     14785|$46,225 |         $31,245 |        68%|           POOR|        5.7|       255|Medium HP|         Car|             15|      109.5091165|    117.5| 77.0| 201.2|      5.572|         30.0|    4/17/2012|
|       Volvo|           C70|      3493|$45,500 |         $34,175 |        75%|           GOOD|        2.3|       236|Medium HP|   Passenger|             23|      101.6233572|    104.9| 71.5| 185.7|      3.601|         18.5|    4/26/2011|
|    Cadillac|       Seville|     15943|$44,475 |         $27,100 |        61%|           POOR|        4.6|       275|Medium HP|   Passenger|             22|      115.6213578|    112.2| 75.0| 201.0|      3.875|         18.5|    4/29/2011|
|     Lincoln|      Town car|     48911|$43,330 |         $21,725 |        50%|           POOR|        4.6|       215|Medium HP|   Passenger|             21|       93.9579169|    117.7| 78.2| 215.3|      4.121|         19.0|     6/4/2012|
+------------+--------------+----------+--------+-----------------+-----------+---------------+-----------+----------+---------+------------+---------------+-----------------+---------+-----+------+-----------+-------------+-------------+
only showing top 20 rows

In [5]:
df_clean = df
for c in ['Price', 'Year Resale Value']:
    df_clean = df_clean.withColumn(c, regexp_replace(col(c), '[^0-9.-]', '').cast('double'))

df_clean.printSchema()

root
 |-- Manufacturer: string (nullable = true)
 |-- Model: string (nullable = true)
 |-- Unit Sales: integer (nullable = true)
 |-- Price: double (nullable = true)
 |-- Year Resale Value: double (nullable = true)
 |-- Retention %: string (nullable = true)
 |-- Retention Value: string (nullable = true)
 |-- Engine Size: double (nullable = true)
 |-- Horsepower: integer (nullable = true)
 |-- HP Level: string (nullable = true)
 |-- Vehicle_type: string (nullable = true)
 |-- Fuel Efficiency: integer (nullable = true)
 |-- Power Perf Factor: double (nullable = true)
 |-- Wheelbase: double (nullable = true)
 |-- Width: double (nullable = true)
 |-- Length: double (nullable = true)
 |-- Curb Weight: double (nullable = true)
 |-- Fuel Capacity: double (nullable = true)
 |-- Latest Launch: string (nullable = true)

In [15]:
df_when1 = df_clean.withColumn('flag',
                 when (col('Year Resale Value')>50000,'Super good')
                .when((col('Year Resale Value') >= 40000) & (col('Year Resale Value') <= 50000), 'Good to buy')
                .when((col('Year Resale Value') >= 30000) & (col('Year Resale Value') < 40000), 'Average')
                .otherwise('Not Good to Buy')) \
                .withColumn('Depreciation',col('Price') - col('Year Resale Value'))\
                .select('Manufacturer', 'Model', 'Price', 'Year Resale Value','Depreciation', 'flag')

df_when1.show()

+------------+--------------+-------+-----------------+------------+---------------+
|Manufacturer|         Model|  Price|Year Resale Value|Depreciation|           flag|
+------------+--------------+-------+-----------------+------------+---------------+
|  Mercedes-B|         CL500|85500.0|          63423.0|     22077.0|     Super good|
|  Mercedes-B|      SL-Class|82600.0|          58600.0|     24000.0|     Super good|
|     Porsche|Carrera Cabrio|74970.0|          67550.0|      7420.0|     Super good|
|  Mercedes-B|         CL500|85500.0|          63423.0|     22077.0|     Super good|
|  Mercedes-B|      SL-Class|82600.0|          58600.0|     24000.0|     Super good|
|     Porsche|Carrera Cabrio|74970.0|          67550.0|      7420.0|     Super good|
|     Porsche| Carrera Coupe|71020.0|          60625.0|     10395.0|     Super good|
|       Dodge|         Viper|69725.0|          58470.0|     11255.0|     Super good|
|  Mercedes-B|       S-Class|69700.0|          50375.0|     19325.0|     Super good|
|        Audi|            A8|62000.0|          39000.0|     23000.0|        Average|
|       Lexus|         LX470|60105.0|          43870.0|     16235.0|    Good to buy|
|   Chevrolet|      Corvette|55705.0|          36225.0|     19480.0|        Average|
|       Lexus|         LS400|54005.0|          40375.0|     13630.0|    Good to buy|
|      Toyota|  Land Cruiser|51728.0|          34080.0|     17648.0|        Average|
|  Mercedes-B|       E-Class|49900.0|          41450.0|      8450.0|    Good to buy|
|       Lexus|         GS400|46305.0|          38955.0|      7350.0|        Average|
|    Cadillac|      Escalade|46225.0|          31245.0|     14980.0|        Average|
|       Volvo|           C70|45500.0|          34175.0|     11325.0|        Average|
|    Cadillac|       Seville|44475.0|          27100.0|     17375.0|Not Good to Buy|
|     Lincoln|      Town car|43330.0|          21725.0|     21605.0|Not Good to Buy|
+------------+--------------+-------+-----------------+------------+---------------+
only showing top 20 rows

In [77]:
df_clean.groupBy('Manufacturer') \
        .agg(avg('Price').alias('Total_Price')) \
        .orderBy(col('Total_Price').desc()) \
        .show()

+------------+------------------+
|Manufacturer|       Total_Price|
+------------+------------------+
|     Porsche|           65597.5|
|  Mercedes-B| 58577.27272727273|
|       Lexus|           44055.0|
|      Jaguar|           42800.0|
|     Lincoln|           41690.0|
|    Cadillac|           40254.0|
|        Audi|           39980.0|
|         BMW|33096.666666666664|
|       Volvo|30933.333333333332|
|       Acura|30633.333333333332|
|        Saab|           29610.0|
|    Infiniti|           29465.0|
|       Buick|          26781.25|
|  Oldsmobile|25622.833333333332|
|       Dodge|24213.636363636364|
|    Chrysler|23430.833333333332|
|     Pontiac|22949.166666666668|
|    Plymouth|           22642.5|
|      Nissan|22360.714285714286|
|  Mitsubishi|22167.428571428572|
+------------+------------------+
only showing top 20 rows

In [10]:
df_When = df.withColumn('Fav', when(col('Manufacturer') == 'Mercedes-B', 'like')\
            .when(col('Manufacturer')== 'Volvo','like')\
            .when(col('Manufacturer')== 'Porsche','Maybe')
            .otherwise('Dislike')) \
            .select('Manufacturer', 'Model', 'Horsepower', 'Fav')

df_When.limit(20).toPandas()

   Manufacturer           Model  Horsepower      Fav
0    Mercedes-B           CL500         NaN     like
1    Mercedes-B        SL-Class         NaN     like
2       Porsche  Carrera Cabrio       300.0    Maybe
3    Mercedes-B           CL500       302.0     like
4    Mercedes-B        SL-Class       302.0     like
5       Porsche  Carrera Cabrio       300.0    Maybe
6       Porsche   Carrera Coupe       300.0    Maybe
7         Dodge           Viper       450.0  Dislike
8    Mercedes-B         S-Class       275.0     like
9          Audi              A8       310.0  Dislike
10        Lexus           LX470       230.0  Dislike
11    Chevrolet        Corvette       345.0  Dislike
12        Lexus           LS400       290.0  Dislike
13       Toyota    Land Cruiser       230.0  Dislike
14   Mercedes-B         E-Class       221.0     like
15        Lexus           GS400       300.0  Dislike
16     Cadillac        Escalade       255.0  Dislike
17        Volvo             C70       236.0     like
18     Cadillac         Seville       275.0  Dislike
19      Lincoln        Town car       215.0  Dislike

In [15]:
fav1 = when(col('Manufacturer') == 'Mercedes-B', 'like')\
            .when(col('Manufacturer')== 'Volvo','like')\
            .when(col('Manufacturer')== 'Porsche','Maybe')\
            .otherwise('Dislike')
            
df_when2 = df.withColumn('fav1', fav1)\
             .select('Manufacturer', 'Model', 'Horsepower', 'Fav1')
             

df_when2.limit(20).toPandas()

   Manufacturer           Model  Horsepower     Fav1
0    Mercedes-B           CL500         NaN     like
1    Mercedes-B        SL-Class         NaN     like
2       Porsche  Carrera Cabrio       300.0    Maybe
3    Mercedes-B           CL500       302.0     like
4    Mercedes-B        SL-Class       302.0     like
5       Porsche  Carrera Cabrio       300.0    Maybe
6       Porsche   Carrera Coupe       300.0    Maybe
7         Dodge           Viper       450.0  Dislike
8    Mercedes-B         S-Class       275.0     like
9          Audi              A8       310.0  Dislike
10        Lexus           LX470       230.0  Dislike
11    Chevrolet        Corvette       345.0  Dislike
12        Lexus           LS400       290.0  Dislike
13       Toyota    Land Cruiser       230.0  Dislike
14   Mercedes-B         E-Class       221.0     like
15        Lexus           GS400       300.0  Dislike
16     Cadillac        Escalade       255.0  Dislike
17        Volvo             C70       236.0     like
18     Cadillac         Seville       275.0  Dislike
19      Lincoln        Town car       215.0  Dislike